import { createHmac, timingSafeEqual } from "node:crypto";
const TOKEN_TTL_SECONDS = 7 * 24 * 60 * 60;
const PURPOSE = "meeting-detail";
function getSecret() { const secret = process.env.IDLE_COOKIE_SECRET; if (!secret || secret.length < 32) throw new Error("IDLE_COOKIE_SECRET must be at least 32 characters"); return secret; }
function sign(value: string) { return createHmac("sha256", getSecret()).update(value).digest("base64url"); }
function encode(value: string) { return Buffer.from(value, "utf8").toString("base64url"); }
function decode(value: string) { return Buffer.from(value, "base64url").toString("utf8"); }
export function createMeetingPublicToken(publicId: string, ttlSeconds = TOKEN_TTL_SECONDS) { const exp = Math.floor(Date.now() / 1000) + ttlSeconds; const payload = encode(JSON.stringify({ p: PURPOSE, id: publicId, exp })); return `${payload}.${sign(payload)}`; }
export function verifyMeetingPublicToken(token: string) { try { const [payload, signature] = token.split("."); if (!payload || !signature || payload.length > 1024 || signature.length > 128) return null; const expected = sign(payload); const actualBuffer = Buffer.from(signature, "base64url"); const expectedBuffer = Buffer.from(expected, "base64url"); if (actualBuffer.length !== expectedBuffer.length || !timingSafeEqual(actualBuffer, expectedBuffer)) return null; const data = JSON.parse(decode(payload)) as { p?: string; id?: string; exp?: number }; const exp = data.exp; if (data.p !== PURPOSE || typeof data.id !== "string" || !/^[0-9a-f-]{36}$/i.test(data.id)) return null; if (typeof exp !== "number" || !Number.isSafeInteger(exp) || exp < Math.floor(Date.now() / 1000)) return null; return { publicId: data.id, expiresAt: new Date(exp * 1000) }; } catch { return null; } }
export function createMeetingPublicUrl(publicId: string, origin?: string) { const base = (origin || process.env.APP_PUBLIC_URL || process.env.NEXT_PUBLIC_APP_URL || "").trim().replace(/\/$/, ""); if (!base) return null; const appBasePath = (process.env.NEXT_PUBLIC_BASE_PATH || "/mycar").trim().replace(/\/$/, ""); return `${base}${appBasePath}/public/meeting-bookings/${createMeetingPublicToken(publicId)}`; }
export function getPublicOrigin(request: Request) { const configured = (process.env.APP_PUBLIC_URL || process.env.NEXT_PUBLIC_APP_URL || "").trim().replace(/\/$/, ""); if (configured) return configured; const forwardedHost = request.headers.get("x-forwarded-host")?.split(",")[0]?.trim(); const forwardedProto = request.headers.get("x-forwarded-proto")?.split(",")[0]?.trim() || "https"; if (forwardedHost && (forwardedProto === "http" || forwardedProto === "https")) return `${forwardedProto}://${forwardedHost}`; const host = request.headers.get("host")?.trim(); if (host) return `${request.url.startsWith("https://") ? "https" : "http"}://${host}`; return new URL(request.url).origin; }
