import { decrypt } from "@/lib/crypto";
import { prisma } from "@/lib/prisma";

export type MeetingNotificationEvent = "MEETING_BOOKING_CREATED" | "MEETING_BOOKING_UPDATED" | "MEETING_BOOKING_CANCELLED";
type NotificationSettings = Record<string, string>;
const eventTitle: Record<MeetingNotificationEvent, string> = { MEETING_BOOKING_CREATED: "มีการจองห้องประชุม", MEETING_BOOKING_UPDATED: "มีการแก้ไขการจองห้องประชุม", MEETING_BOOKING_CANCELLED: "มีการยกเลิกจองห้องประชุม" };
const MOPH_ALERT_PROD_URL = "https://morpromt2c.moph.go.th";
const MOPH_NOTIFY_PROD_URL = "https://morpromt2f.moph.go.th";
const MOPH_REQUEST_TIMEOUT_MS = 10_000;
type MophResult = { success: boolean; httpStatus: number | null; messageCode: number | null; responseMessage: string | null; error: string | null };
async function getNotificationSettings(): Promise<NotificationSettings> { const rows = await prisma.notificationSetting.findMany({ where: { key: { in: ["MOPH_NOTIFY_BASE_URL", "MOPH_NOTIFY_CLIENT_KEY", "MOPH_NOTIFY_SECRET_KEY", "MOPH_NOTIFY_GROUP_BASE_URL", "MOPH_NOTIFY_GROUP_ENABLED", "MOPH_NOTIFY_GROUP_CLIENT_KEY", "MOPH_NOTIFY_GROUP_SECRET_KEY"] } } }); return Object.fromEntries(rows.map((row) => [row.key, row.value ?? ""])); }
export function buildMeetingNotificationMessage(input: { eventType: MeetingNotificationEvent; roomName: string; title: string; startAt: Date; endAt: Date; status: string; requesterName?: string | null; departmentName?: string | null; detailUrl?: string | null }) { const date = input.startAt.toLocaleDateString("th-TH"); const startTime = input.startAt.toLocaleTimeString("th-TH", { hour: "2-digit", minute: "2-digit" }); const endTime = input.endAt.toLocaleTimeString("th-TH", { hour: "2-digit", minute: "2-digit" }); const link = input.detailUrl ? `\n\n🔗 ดูรายละเอียดการจอง\n${input.detailUrl}` : ""; return `${eventTitle[input.eventType]}\n👤 ผู้จอง: ${input.requesterName?.trim() || "ไม่ระบุ"}\n🏢 กลุ่มงาน: ${input.departmentName?.trim() || "ไม่ระบุกลุ่มงาน"}\n🏨 ห้องประชุม: ${input.roomName}\n📌 เรื่อง: ${input.title}\n🗓️ วันที่: ${date}\n⏰ เวลา: ${startTime}-${endTime}\n📊 สถานะ: ${input.status}${link}`; }
export async function createMeetingBookingNotification(input: { requesterId: string; bookingId?: string; publicId: string; roomName: string; title: string; startAt: Date; endAt: Date; status: string; eventType: MeetingNotificationEvent; requesterName?: string | null; departmentName?: string | null; detailUrl?: string | null }) { const message = buildMeetingNotificationMessage(input); return prisma.notification.create({ data: { userId: input.requesterId, channel: "IN_APP", type: input.eventType, title: eventTitle[input.eventType], message, resource: "MEETING_BOOKING", resourceId: input.publicId, status: "PENDING", metadata: { bookingPublicId: input.publicId, bookingId: input.bookingId ?? null, detailUrl: input.detailUrl ?? null } } }); }
export async function sendMophNotifyMeetingEvent(input: { requesterId: string; publicId: string; eventType: MeetingNotificationEvent; message: string; detailUrl?: string | null }) { const [settings, user] = await Promise.all([getNotificationSettings(), prisma.user.findUnique({ where: { id: input.requesterId }, select: { id: true, cidCiphertext: true, providerIdentity: { select: { cidCiphertext: true } } } })]); const individualClientKey = settings.MOPH_NOTIFY_CLIENT_KEY || process.env.MOPH_NOTIFY_CLIENT_KEY || ""; const individualSecretKey = settings.MOPH_NOTIFY_SECRET_KEY || process.env.MOPH_NOTIFY_SECRET_KEY || ""; const groupClientKey = settings.MOPH_NOTIFY_GROUP_CLIENT_KEY || process.env.MOPH_NOTIFY_GROUP_CLIENT_KEY || process.env.MOPH_CLIENT_KEY || ""; const groupSecretKey = settings.MOPH_NOTIFY_GROUP_SECRET_KEY || process.env.MOPH_NOTIFY_GROUP_SECRET_KEY || process.env.MOPH_SECRET_KEY || ""; const groupBaseUrl = settings.MOPH_NOTIFY_GROUP_BASE_URL || process.env.MOPH_NOTIFY_GROUP_BASE_URL || process.env.MOPH_URL || MOPH_NOTIFY_PROD_URL; const groupEnabled = (settings.MOPH_NOTIFY_GROUP_ENABLED || process.env.MOPH_NOTIFY_GROUP_ENABLED || "false").toLowerCase() === "true"; const title = eventTitle[input.eventType]; const results = { individual: false, group: false };
if (!individualClientKey || !individualSecretKey) await safeRecordMophFailure({ ...input, reason: "MOPH_ALERT_CREDENTIALS_MISSING", detail: "ยังไม่ได้ตั้งค่า client-key และ secret-key สำหรับ MOPH Alert รายบุคคล", destination: "INDIVIDUAL", endpoint: "/alert/v3.1/messages" }); else { let cid: string | null = null; try { const encryptedCid = user?.providerIdentity?.cidCiphertext ?? user?.cidCiphertext ?? ""; const decrypted = decrypt(encryptedCid); if (/^\d{13}$/.test(decrypted)) cid = decrypted; } catch {} if (!cid) await safeRecordMophFailure({ ...input, reason: "USER_CID_NOT_AVAILABLE", detail: "ไม่มี CID 13 หลักที่ใช้งานได้สำหรับการส่งรายบุคคล", destination: "INDIVIDUAL", endpoint: "/alert/v3.1/messages" }); else { const result = await safelyPostMophAlertFreeForm({ baseUrl: settings.MOPH_NOTIFY_BASE_URL || MOPH_ALERT_PROD_URL, clientKey: individualClientKey, secretKey: individualSecretKey, cid, title, message: input.message }); results.individual = result.success; await safeRecordMophResult(input, title, "INDIVIDUAL", result); } }
if (groupEnabled) { if (!groupClientKey || !groupSecretKey) await safeRecordMophFailure({ ...input, reason: "MOPH_NOTIFY_GROUP_CREDENTIALS_MISSING", detail: "เปิดส่ง LINE กลุ่มแล้ว แต่ยังไม่ได้ตั้งค่า client-key และ secret-key จาก CMS MOPH Notify", destination: "GROUP", endpoint: "/mycar/api/notify/send" }); else { const result = await safelyPostMophNotifyGroup({ baseUrl: groupBaseUrl, clientKey: groupClientKey, secretKey: groupSecretKey, message: input.message }); results.group = result.success; await safeRecordMophResult(input, title, "GROUP", result); } } if (!results.individual && !results.group) throw new Error("MOPH Notify ส่งไม่สำเร็จทั้งรายบุคคลและ LINE กลุ่ม"); return results; }
function normalizeEndpoint(value: string, path: string) { const url = value.trim().replace(/\/$/, ""); return url.endsWith(path) ? url : `${url}${path}`; }
async function postMophAlertFreeForm(input: { baseUrl: string; clientKey: string; secretKey: string; cid: string; title: string; message: string }) { const htmlMessage = escapeHtml(input.message).replace(/\n/g, "<br />"); const response = await fetch(normalizeEndpoint(input.baseUrl, "/alert/v3.1/messages"), { method: "POST", headers: { "Content-Type": "application/json", "client-key": input.clientKey, "secret-key": input.secretKey }, body: JSON.stringify({ cid: [input.cid], messages: [{ text: input.message, type: "text" }], message_title: input.title, message_html: `<div><strong>${escapeHtml(input.title)}</strong><br>${htmlMessage}</div>`, message_text: input.message, message_type: "HPT" }), cache: "no-store", signal: AbortSignal.timeout(MOPH_REQUEST_TIMEOUT_MS) }); return parseMophResponse(response); }
export async function sendMophNotifyGroupTest(message: string) { const settings = await getNotificationSettings(); const clientKey = settings.MOPH_NOTIFY_GROUP_CLIENT_KEY || process.env.MOPH_NOTIFY_GROUP_CLIENT_KEY || process.env.MOPH_CLIENT_KEY || ""; const secretKey = settings.MOPH_NOTIFY_GROUP_SECRET_KEY || process.env.MOPH_NOTIFY_GROUP_SECRET_KEY || process.env.MOPH_SECRET_KEY || ""; const baseUrl = settings.MOPH_NOTIFY_GROUP_BASE_URL || process.env.MOPH_NOTIFY_GROUP_BASE_URL || process.env.MOPH_URL || MOPH_NOTIFY_PROD_URL; if (!clientKey || !secretKey) return { success: false, httpStatus: null, messageCode: null, responseMessage: null, error: "ยังไม่ได้ตั้งค่า client-key / secret-key ของ MOPH Notify กลุ่ม" }; return safelyPostMophNotifyGroup({ baseUrl, clientKey, secretKey, message }); }
async function postMophNotifyGroup(input: { baseUrl: string; clientKey: string; secretKey: string; message: string }) { const response = await fetch(normalizeEndpoint(input.baseUrl, "/mycar/api/notify/send"), { method: "POST", headers: { "Content-Type": "application/json", "client-key": input.clientKey, "secret-key": input.secretKey }, body: JSON.stringify({ messages: [{ type: "text", text: input.message }] }), cache: "no-store", signal: AbortSignal.timeout(MOPH_REQUEST_TIMEOUT_MS) }); return parseMophResponse(response); }
async function safelyPostMophAlertFreeForm(input: Parameters<typeof postMophAlertFreeForm>[0]): Promise<MophResult> { try { return await postMophAlertFreeForm(input); } catch (error) { return mophTransportFailure(error); } }
async function safelyPostMophNotifyGroup(input: Parameters<typeof postMophNotifyGroup>[0]): Promise<MophResult> { try { return await postMophNotifyGroup(input); } catch (error) { return mophTransportFailure(error); } }
function mophTransportFailure(error: unknown): MophResult { const message = error instanceof Error ? error.message : "Unknown transport error"; return { success: false, httpStatus: null, messageCode: null, responseMessage: null, error: `Request failed: ${message}` }; }
async function parseMophResponse(response: Response): Promise<MophResult> { const payload = await response.json().catch(() => null) as { message_code?: number; message?: string } | null; const responseMessage = payload?.message ?? null; const normalizedMessage = responseMessage?.trim().toLowerCase() ?? ""; const successMessage = normalizedMessage === "success" || normalizedMessage === "succesfully" || normalizedMessage === "successfully"; const success = response.ok && (payload?.message_code === 200 || successMessage); return { success, httpStatus: response.status, messageCode: payload?.message_code ?? null, responseMessage, error: success ? null : responseMessage ?? `HTTP ${response.status}` }; }
async function safeRecordMophResult(input: Parameters<typeof recordMophResult>[0], title: string, destination: "INDIVIDUAL" | "GROUP", result: MophResult) { try { await recordMophResult(input, title, destination, result); } catch (error) { console.error("Failed to persist MOPH notification result", error); } }
async function safeRecordMophFailure(input: Parameters<typeof recordMophFailure>[0]) { try { await recordMophFailure(input); } catch (error) { console.error("Failed to persist MOPH notification failure", error); } }
async function recordMophResult(input: { requesterId: string; publicId: string; eventType: MeetingNotificationEvent; message: string; detailUrl?: string | null }, title: string, destination: "INDIVIDUAL" | "GROUP", result: MophResult) { await prisma.notification.create({ data: { userId: input.requesterId, channel: "MOHP_NOTIFY", type: input.eventType, title, message: input.message, resource: "MEETING_BOOKING", resourceId: input.publicId, status: result.success ? "SENT" : "FAILED", sentAt: result.success ? new Date() : null, failedAt: result.success ? null : new Date(), error: result.success ? null : result.error, metadata: { destination, endpoint: destination === "INDIVIDUAL" ? "/alert/v3.1/messages" : "/mycar/api/notify/send", httpStatus: result.httpStatus, messageCode: result.messageCode, responseMessage: result.responseMessage, detailUrl: input.detailUrl ?? null } } }); }
async function recordMophFailure(input: { requesterId: string; publicId: string; eventType: MeetingNotificationEvent; message: string; detail: string; destination: "INDIVIDUAL" | "GROUP"; endpoint: string; reason: string; detailUrl?: string | null }) { await prisma.notification.create({ data: { userId: input.requesterId, channel: "MOHP_NOTIFY", type: input.eventType, title: eventTitle[input.eventType], message: input.message, resource: "MEETING_BOOKING", resourceId: input.publicId, status: "FAILED", failedAt: new Date(), error: input.reason, metadata: { reason: input.reason, detail: input.detail, destination: input.destination, endpoint: input.endpoint, detailUrl: input.detailUrl ?? null } } }); }
function escapeHtml(value: string) { return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;").replace(/'/g, "&#039;"); }
