"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, Building2, CheckCircle2, Loader2 } from "lucide-react";
import { useRouter } from "next/navigation";

type Department = { publicId: string; abbreviation: string | null; nameTh: string };

export default function DepartmentSetupPage() {
  const router = useRouter(); const [departments, setDepartments] = useState<Department[]>([]); const [departmentId, setDepartmentId] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { fetch("/mycar/api/v1/departments/available", { cache: "no-store" }).then(async r => { const p = await r.json(); if (!r.ok) throw new Error(p.error ?? "ไม่สามารถโหลดข้อมูลแผนกได้"); setDepartments(p.data ?? []); }).catch(e => setError(e instanceof Error ? e.message : "ไม่สามารถโหลดข้อมูลแผนกได้")).finally(() => setLoading(false)); }, []);
  async function submit(e: React.FormEvent) { e.preventDefault(); if (!departmentId) { setError("กรุณาเลือกแผนกก่อนยืนยัน"); return; } setSaving(true); setError(""); try { const r = await fetch("/mycar/api/v1/users/me/department", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ departmentId }) }); const p = await r.json().catch(() => ({})); if (!r.ok) throw new Error(p.error === "DEPARTMENT_ALREADY_SET" ? "มีข้อมูลแผนกของคุณอยู่แล้ว" : p.error ?? "ไม่สามารถบันทึกแผนกได้"); router.replace("/portal"); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "ไม่สามารถบันทึกแผนกได้"); setSaving(false); } }
  return <main className="min-h-screen bg-slate-50 px-4 py-8 sm:px-6 sm:py-12"><div className="mx-auto flex min-h-[calc(100vh-4rem)] max-w-2xl items-center justify-center"><section className="w-full rounded-[2rem] border border-slate-200 bg-white p-6 shadow-xl shadow-slate-900/5 sm:p-10"><div className="flex size-14 items-center justify-center rounded-2xl bg-teal-50 text-teal-700"><Building2 size={26}/></div><p className="mt-6 text-sm font-semibold text-teal-700">ตั้งค่าข้อมูลผู้ใช้งานครั้งแรก</p><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-900">เลือกแผนกของคุณ</h1><p className="mt-3 leading-7 text-slate-600">กรุณาเลือกแผนกที่สังกัดเพื่อใช้งานระบบที่ต้องใช้ข้อมูลหน่วยงาน เช่น ระบบขอใช้รถยนต์</p>{loading?<div className="mt-8 flex items-center gap-2 rounded-2xl bg-slate-50 p-4 text-sm text-slate-500" role="status"><Loader2 size={18} className="animate-spin"/>กำลังโหลดรายการแผนก...</div>:departments.length===0?<div className="mt-8 space-y-4"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-800"><p className="font-bold">ยังไม่มีแผนกที่พร้อมให้เลือก</p><p className="mt-1">ขณะนี้ยังไม่มีข้อมูลแผนก Active ในระบบ คุณจึงยังไม่สามารถกำหนดแผนกได้ หากต้องการใช้งานระบบจองห้องประชุม สามารถกลับไปที่ Health Portal ได้ทันที</p></div>{error?<div role="alert" className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>:null}<Link href="/portal" className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-slate-950 px-5 py-3 text-sm font-bold text-white hover:bg-slate-800"><ArrowLeft size={18}/>กลับไป Health Portal</Link></div>:<form onSubmit={submit} className="mt-8 space-y-5"><div><label className="block text-sm font-bold text-slate-700" htmlFor="department">แผนก</label><p className="mt-1 text-xs text-slate-500">แสดงเฉพาะชื่อแผนกและตัวย่อ ไม่แสดง ID หรือรหัสภายในระบบ</p></div><select id="department" value={departmentId} onChange={e=>setDepartmentId(e.target.value)} className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-4 text-base outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-100" disabled={saving}><option value="">เลือกแผนกของคุณ</option>{departments.map(d=><option key={d.publicId} value={d.publicId}>{d.nameTh}{d.abbreviation ? ` — ${d.abbreviation}` : ""}</option>)}</select>{error?<div role="alert" className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>:null}<button type="submit" disabled={saving||!departmentId} className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-slate-950 px-5 py-3 text-sm font-bold text-white hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-50">{saving?<Loader2 size={18} className="animate-spin"/>:<CheckCircle2 size={18}/>} {saving?"กำลังบันทึก...":"ยืนยันแผนกและเข้าใช้งาน"}</button></form>}</section></div></main>;
}
