import { NextResponse } from "next/server";
import type { Prisma } from "@/generated/prisma/client";
import { getCurrentUser } from "@/modules/identity/session";
import { hasPermission } from "@/lib/authorization";
import { prisma } from "@/lib/prisma";
import { buildMeetingNotificationMessage, createMeetingBookingNotification, sendMophNotifyMeetingEvent } from "@/lib/notifications";
import { createMeetingPublicUrl, getPublicOrigin } from "@/lib/meeting-public-link";
const ACTIONS=["START_PREPARATION","MARK_READY","COMPLETE","BACK","CANCEL","UNAPPROVE"] as const;
function requesterName(u:{nameTh:string|null;firstnameTh:string|null;lastnameTh:string|null}){return u.nameTh?.trim()||[u.firstnameTh,u.lastnameTh].filter(Boolean).join(" ").trim()||null;}
export async function PATCH(req:Request){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const admin=user.roles.some(({role})=>["SUPER_ADMIN","ADMIN"].includes(role.key));const canManage=admin||await hasPermission(user.id,"APPROVE_MEETING_BOOKINGS");if(!canManage)return NextResponse.json({error:"FORBIDDEN"},{status:403});const body=await req.json();const id=String(body.id||"");const action=String(body.action||"");const reason=body.reason?String(body.reason).trim():"";if(!ACTIONS.includes(action as (typeof ACTIONS)[number]))return NextResponse.json({error:"การดำเนินการไม่ถูกต้อง"},{status:400});const b=await prisma.meetingBooking.findUnique({where:{publicId:id},include:{room:{select:{nameTh:true}},requester:{select:{nameTh:true,firstnameTh:true,lastnameTh:true,department:{select:{nameTh:true}}}},evaluation:{select:{id:true}}}});if(!b)return NextResponse.json({error:"ไม่พบรายการจอง"},{status:404});
if(action==="UNAPPROVE"){if(b.status!=="APPROVED")return NextResponse.json({error:"ยกเลิกการอนุมัติได้เฉพาะรายการที่อนุมัติแล้ว"},{status:409});const u=await prisma.meetingBooking.update({where:{id:b.id},data:{status:"PENDING",approvedById:null,approvedAt:null,preparedById:null,preparedAt:null,preparationStatus:"NOT_STARTED",updatedAt:new Date()},select:{publicId:true,status:true,preparationStatus:true,preparedAt:true,preparedById:true}});const input={requesterId:b.requesterId,bookingId:b.id,publicId:b.publicId,roomName:b.room.nameTh,title:b.title,startAt:b.startAt,endAt:b.endAt,status:u.status,eventType:"MEETING_BOOKING_UPDATED" as const,requesterName:requesterName(b.requester),departmentName:b.requester.department?.nameTh??null,detailUrl:createMeetingPublicUrl(b.publicId,getPublicOrigin(req))};const message=`${buildMeetingNotificationMessage(input)}\n⚠️ การอนุมัติถูกยกเลิก รายการกลับไปเป็นสถานะรออนุมัติ`;try{await createMeetingBookingNotification(input)}catch(error){console.error("IN_APP meeting unapprove notification failed",error)}try{await sendMophNotifyMeetingEvent({...input,message})}catch(error){console.error("MOPH Notify meeting unapprove failed",error)}await prisma.auditLog.create({data:{userId:user.id,action:"UNAPPROVE_MEETING_BOOKING",resource:"MEETING_BOOKING",resourceId:b.publicId,result:"SUCCESS"}});return NextResponse.json({booking:u});}
if(action==="CANCEL"){if(!["APPROVED"].includes(b.status))return NextResponse.json({error:"ยกเลิกได้เฉพาะรายการที่อนุมัติแล้ว"},{status:409});if(!reason)return NextResponse.json({error:"กรุณาระบุเหตุผลการยกเลิก"},{status:400});const u=await prisma.meetingBooking.update({where:{id:b.id},data:{status:"CANCELLED",cancellationReason:reason,cancelledAt:new Date(),updatedAt:new Date()},select:{publicId:true,status:true,preparationStatus:true,preparedAt:true,preparedById:true}});const input={requesterId:b.requesterId,bookingId:b.id,publicId:b.publicId,roomName:b.room.nameTh,title:b.title,startAt:b.startAt,endAt:b.endAt,status:u.status,eventType:"MEETING_BOOKING_CANCELLED" as const,requesterName:requesterName(b.requester),departmentName:b.requester.department?.nameTh??null,detailUrl:createMeetingPublicUrl(b.publicId,getPublicOrigin(req))};const message=`${buildMeetingNotificationMessage(input)}\n📝 เหตุผลการยกเลิก: ${reason}`;try{await createMeetingBookingNotification(input)}catch(error){console.error("IN_APP meeting cancellation notification failed",error)}try{await sendMophNotifyMeetingEvent({...input,message})}catch(error){console.error("MOPH Notify meeting cancellation failed",error)}await prisma.auditLog.create({data:{userId:user.id,action:"CANCEL_MEETING_BOOKING",resource:"MEETING_BOOKING",resourceId:b.publicId,result:"SUCCESS",metadata:{cancellationReason:reason}}});return NextResponse.json({booking:u});}
if(b.status!=="APPROVED"&&!(action==="BACK"&&b.status==="COMPLETED"))return NextResponse.json({error:"รายการนี้ไม่อยู่ในสถานะที่จัดการได้"},{status:409});if(b.preparedById!==user.id&&!admin)return NextResponse.json({error:"งานเตรียมห้องนี้เป็นของผู้ที่กดอนุมัติรายการเท่านั้น"},{status:403});let data: Prisma.MeetingBookingUpdateInput;if(action==="START_PREPARATION"){if(b.preparationStatus!=="NOT_STARTED")return NextResponse.json({error:"กรุณาใช้สถานะปัจจุบันตามลำดับ"},{status:409});data={preparationStatus:"IN_PROGRESS",preparedAt:null,updatedAt:new Date()};}else if(action==="MARK_READY"){if(b.preparationStatus!=="IN_PROGRESS")return NextResponse.json({error:"กรุณาเริ่มเตรียมห้องก่อน"},{status:409});data={preparationStatus:"READY",preparedAt:new Date(),updatedAt:new Date()};}else if(action==="COMPLETE"){if(b.preparationStatus!=="READY")return NextResponse.json({error:"กรุณาทำให้ห้องพร้อมใช้งานก่อน"},{status:409});data={status:"COMPLETED",updatedAt:new Date()};}else{if(b.evaluation)return NextResponse.json({error:"รายการนี้มีผลประเมินแล้ว ไม่สามารถย้อนสถานะได้"},{status:409});if(b.status==="COMPLETED"&&b.preparationStatus==="READY")data={status:"APPROVED",preparationStatus:"IN_PROGRESS",preparedAt:null,updatedAt:new Date()};else if(b.preparationStatus==="READY")data={preparationStatus:"IN_PROGRESS",preparedAt:null,updatedAt:new Date()};else if(b.preparationStatus==="IN_PROGRESS")data={preparationStatus:"NOT_STARTED",preparedAt:null,updatedAt:new Date()};else return NextResponse.json({error:"ไม่มีสถานะก่อนหน้าให้ย้อนกลับ"},{status:409});}const u=await prisma.meetingBooking.update({where:{id:b.id},data,select:{publicId:true,status:true,preparationStatus:true,preparedAt:true,preparedById:true}});await prisma.auditLog.create({data:{userId:user.id,action:action+"_MEETING_BOOKING",resource:"MEETING_BOOKING",resourceId:b.publicId,result:"SUCCESS"}});return NextResponse.json({booking:u});}
