import { requireAdmin } from "@/lib/authorization";
import { prisma } from "@/lib/prisma";

export default async function AuditPage() {
  await requireAdmin();
  const cutoff = new Date(); cutoff.setDate(cutoff.getDate() - 90);
  const logs = await prisma.auditLog.findMany({ where: { createdAt: { gte: cutoff } }, take: 100, orderBy: { createdAt: "desc" }, include: { user: { select: { nameTh: true, firstnameTh: true, lastnameTh: true } } } });
  return <div className="space-y-6"><div><p className="text-sm font-semibold text-teal-700">ระบบ</p><h1 className="mt-1 text-3xl font-black text-slate-900">ประวัติการใช้งาน</h1><p className="mt-2 text-sm text-slate-500">เก็บและแสดงประวัติการใช้งานย้อนหลังไม่เกิน 90 วัน รายการที่เก่ากว่านี้จะถูกลบออกจากฐานข้อมูลโดยกระบวนการรักษาข้อมูล</p></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-4">วันเวลา</th><th className="px-5 py-4">ผู้ใช้งาน</th><th className="px-5 py-4">กิจกรรม</th><th className="px-5 py-4">รายการ</th><th className="px-5 py-4">ผลลัพธ์</th></tr></thead><tbody className="divide-y divide-slate-100">{logs.map((log) => { const actor = log.user?.nameTh ?? ([log.user?.firstnameTh, log.user?.lastnameTh].filter(Boolean).join(" ") || "System"); return <tr key={log.id}><td className="whitespace-nowrap px-5 py-4 text-slate-500">{new Intl.DateTimeFormat("th-TH", { dateStyle: "short", timeStyle: "medium" }).format(log.createdAt)}</td><td className="px-5 py-4 font-semibold text-slate-700">{actor}</td><td className="px-5 py-4 font-semibold text-slate-700">{log.action}</td><td className="px-5 py-4 text-slate-500">{log.resource}{log.resourceId ? ` • ${log.resourceId.slice(0, 8)}…` : ""}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${log.result === "SUCCESS" ? "bg-emerald-50 text-emerald-700" : log.result === "DENIED" ? "bg-amber-50 text-amber-700" : "bg-red-50 text-red-700"}`}>{log.result}</span></td></tr>; })}</tbody></table>{logs.length === 0 ? <div className="p-12 text-center text-sm text-slate-400">ยังไม่มีประวัติการใช้งานใน 90 วันล่าสุด</div> : null}</div></div></div>;
}
