"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { CarFront, MapPin, Users, X, ChevronLeft, ChevronRight } from "lucide-react";

type RequestItem = { id:string; departureDate:string; departureTime:string; returnDate:string; returnTime:string; destination:string; purpose:string; passengerCount:number; requester:string; department:string; status:string; vehicle:string|null; driver:string|null };
type DayCell={date:string;day:number;currentMonth:boolean;today:boolean};
const thaiMonths=["มกราคม","กุมภาพันธ์","มีนาคม","เมษายน","พฤษภาคม","มิถุนายน","กรกฎาคม","สิงหาคม","กันยายน","ตุลาคม","พฤศจิกายน","ธันวาคม"], thaiDays=["จ","อ","พ","พฤ","ศ","ส","อา"];
const timeFormatter=new Intl.DateTimeFormat("th-TH",{timeZone:"Asia/Bangkok",hour:"2-digit",minute:"2-digit",hour12:false});
function timeText(v:string){return `${timeFormatter.format(new Date(v))} น.`}
function dateText(v:string){return new Intl.DateTimeFormat("th-TH-u-ca-buddhist",{timeZone:"Asia/Bangkok",day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(v));}
export default function DashboardVehicleCalendar({year,month,requests}:{year:number;month:number;requests:RequestItem[]}){

 const [selectedDate,setSelectedDate]=useState<string|null>(null);
 const first=new Date(Date.UTC(year,month,1)); const daysInMonth=new Date(Date.UTC(year,month+1,0)).getUTCDate(); const startOffset=first.getUTCDay()===0?6:first.getUTCDay()-1; const cells:DayCell[]=[]; const today=new Date(); const todayKey=keyOf(new Date(Date.UTC(today.getFullYear(),today.getMonth(),today.getDate())));
 for(let i=0;i<startOffset;i++){const d=new Date(Date.UTC(year,month,1-(startOffset-i)));cells.push({date:keyOf(d),day:d.getUTCDate(),currentMonth:false,today:false});}
 for(let day=1;day<=daysInMonth;day++){const d=new Date(Date.UTC(year,month,day));const date=keyOf(d);cells.push({date,day,currentMonth:true,today:date===todayKey});}
 while(cells.length%7){const d=new Date(Date.UTC(year,month,daysInMonth+(cells.length-(startOffset+daysInMonth))+1));cells.push({date:keyOf(d),day:d.getUTCDate(),currentMonth:false,today:false});}
 const byDate=useMemo(()=>{const map=new Map<string,RequestItem[]>();for(const r of requests){const key=r.departureDate.slice(0,10);const list=map.get(key)??[];list.push(r);map.set(key,list);}return map;},[requests]); const selected=selectedDate?byDate.get(selectedDate)??[]:[];
 function monthHref(offset:number){const next=new Date(Date.UTC(year,month+offset,1));return `/dashboard?year=${next.getUTCFullYear()}&month=${next.getUTCMonth()+1}`;}
 return <><section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><h2 className="font-black text-slate-900">ปฏิทินการขอใช้รถ</h2><p className="mt-1 text-xs text-slate-500">จำนวนคำขอในแต่ละวัน • กดวันที่เพื่อดูรายละเอียด</p></div><div className="flex items-center gap-2"><Link href={monthHref(-1)} aria-label="เดือนที่ผ่านมา" className="grid size-8 place-items-center rounded-lg border border-slate-200 text-slate-600 hover:bg-slate-50"><ChevronLeft size={17}/></Link><span className="min-w-32 text-center text-sm font-bold text-slate-700">{thaiMonths[month]} {year+543}</span><Link href={monthHref(1)} aria-label="เดือนถัดไป" className="grid size-8 place-items-center rounded-lg border border-slate-200 text-slate-600 hover:bg-slate-50"><ChevronRight size={17}/></Link></div></div><div className="grid grid-cols-7 border-b border-slate-100 bg-slate-50">{thaiDays.map(day=><div key={day} className="px-2 py-2 text-center text-[11px] font-bold text-slate-500">{day}</div>)}</div><div className="grid grid-cols-7">{cells.map(cell=>{const items=byDate.get(cell.date)??[];return <button type="button" key={cell.date} disabled={!cell.currentMonth} onClick={()=>cell.currentMonth&&setSelectedDate(cell.date)} className={`min-h-24 border-b border-r border-slate-100 p-2 text-left transition ${cell.currentMonth?"bg-white hover:bg-teal-50/50":"bg-slate-50/60 text-slate-300"}`}><div className="flex items-center justify-between"><span className={`grid size-7 place-items-center rounded-full text-xs font-bold ${cell.today?"bg-teal-600 text-white":cell.currentMonth?"text-slate-700":"text-slate-300"}`}>{cell.day}</span>{items.length?<span className="rounded-full bg-teal-50 px-2 py-0.5 text-[10px] font-black text-teal-700">{items.length} รายการ</span>:null}</div>{cell.currentMonth?<div className="mt-2 flex min-h-7 flex-wrap items-center gap-1">{items.slice(0,5).map((item,i)=><CarFront key={`${item.id}-${i}`} size={15} className="text-teal-600"/>)}{items.length>5?<span className="text-[10px] font-bold text-slate-400">+{items.length-5}</span>:null}</div>:null}{cell.currentMonth&&!items.length?<span className="mt-2 block text-[10px] text-slate-300">ว่าง</span>:null}</button>})}</div></section>
 {selectedDate?<div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/40 p-4 sm:items-center" onClick={()=>setSelectedDate(null)}><div className="max-h-[85vh] w-full max-w-2xl overflow-hidden rounded-3xl bg-white shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h3 className="font-black text-slate-900">รายละเอียดการขอใช้รถ</h3><p className="mt-1 text-xs text-slate-500">{dateText(selected[0]?.departureDate??`${selectedDate}T00:00:00Z`)} • {selected.length} รายการ</p></div><button type="button" onClick={()=>setSelectedDate(null)} className="grid size-9 place-items-center rounded-lg hover:bg-slate-100"><X size={18}/></button></div><div className="max-h-[65vh] divide-y divide-slate-100 overflow-y-auto">{selected.length===0?<div className="p-10 text-center text-sm text-slate-500">ไม่มีรายการ</div>:selected.map(item=><div key={item.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold text-slate-900">{item.destination}</p><p className="mt-1 text-xs text-slate-500">{dateText(item.departureDate)} {timeText(item.departureTime)} → {dateText(item.returnDate)} {timeText(item.returnTime)} • {item.purpose}</p></div><Status status={item.status}/></div><div className="mt-3 grid gap-2 text-xs text-slate-600 sm:grid-cols-2"><span className="flex items-center gap-2"><Users size={14} className="text-teal-600"/>{item.requester} • {item.department||"ไม่ระบุแผนก"}</span><span className="flex items-center gap-2"><CarFront size={14} className="text-teal-600"/>{item.vehicle??"ยังไม่จัดรถ"}</span><span className="flex items-center gap-2"><MapPin size={14} className="text-teal-600"/>ผู้โดยสาร {item.passengerCount} คน</span><span>พนักงานขับรถ: {item.driver??"ยังไม่จัด"}</span></div></div>)}</div></div></div>:null}</>;
}
function keyOf(d:Date){return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}-${String(d.getUTCDate()).padStart(2,"0")}`;}
function Status({status}:{status:string}){const labels:Record<string,string>={PENDING:"รอพิจารณา",APPROVED:"อนุมัติ",REJECTED:"ไม่อนุมัติ",CANCELLED:"ยกเลิก",COMPLETED:"เสร็จสิ้น"};return <span className="rounded-full bg-amber-50 px-3 py-1 text-[11px] font-bold text-amber-700">{labels[status]??status}</span>}


