"use client";
import { useCallback, useEffect, useState } from "react";
import { Download, FileSpreadsheet, FileText, Filter, RefreshCw, Star, UsersRound, DoorOpen, ClipboardCheck, BarChart3, CalendarDays, Building2, UserRound, ShieldCheck, Boxes, Search, ChevronDown } from "lucide-react";
import Link from "next/link";
import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import DatePicker from "@/components/date-picker";

type MeetingReportRow={[key:string]:string|number|null|undefined;name?:string;id?:string;publicId?:string;startAt?:string;bookings?:number;hours?:number;attendees?:number;completed?:number;capacity?:number;count?:number;equipment?:number;cleanliness?:number;facilitation?:number;suitability?:number;overall?:number;issues?:number;last?:string|null;assigned?:number;notStarted?:number;inProgress?:number;ready?:number;avgPreparationLeadHours?:number;code?:string|null;bookingCount?:number;quantity?:number;month?:string;evaluations?:number;hour?:number;room?:string;department?:string;requester?:string;title?:string;status?:string;cancellationReason?:string;preparedBy?:string;preparationStatus?:string;evaluation?:number|string|null;nameTh?:string;publicId2?:string};
type MasterRow={publicId:string;nameTh:string;capacity?:number;code?:string;firstnameTh?:string|null;lastnameTh?:string|null};
type ExportRow={วันที่:string;ห้อง:string|undefined;หน่วยงาน:string|undefined;ผู้ขอ:string|undefined;หัวข้อ:string|undefined;สถานะ:string;เหตุผลยกเลิก:string;ผู้ดูแล:string|undefined};
type Data={summary?:{total?:number;usedHours?:number;avgOverall?:number;evaluationCount?:number;pending?:number;approved?:number;completed?:number;rejected?:number;cancelled?:number;evaluated?:number;avgDecisionHours?:number;reason?:string;avgEquipment?:number;avgCleanliness?:number;avgFacilitation?:number;avgSuitability?:number};masters?:{rooms:MasterRow[];departments:MasterRow[];preparers:MasterRow[]};trend?:MeetingReportRow[];peakHours?:MeetingReportRow[];bookings?:MeetingReportRow[];rooms?:MeetingReportRow[];departments?:MeetingReportRow[];requesters?:MeetingReportRow[];approvers?:MeetingReportRow[];individual?:MeetingReportRow[];workload?:MeetingReportRow[];equipment?:MeetingReportRow[];issues?:MeetingReportRow[];rejectedReasons?:MeetingReportRow[]};
const fmt=(d:string|null|undefined)=>d?new Intl.DateTimeFormat("th-TH",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(d)):"-";
const status=(x:string)=>({PENDING:"รออนุมัติ",APPROVED:"อนุมัติแล้ว",REJECTED:"ปฏิเสธ",CANCELLED:"ยกเลิก",COMPLETED:"เสร็จสิ้น"}[x]||x);
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const currentMonth=()=>{const n=new Date();return {from:iso(new Date(n.getFullYear(),n.getMonth(),1)),to:iso(new Date(n.getFullYear(),n.getMonth()+1,0))}};
const userName=(x:MasterRow)=>x?.nameTh||[x?.firstnameTh,x?.lastnameTh].filter(Boolean).join(" ")||"ไม่ระบุ";

export default function MeetingReports(){
 const cm=currentMonth();
 const [from,setFrom]=useState("");const [to,setTo]=useState("");const [roomId,setRoomId]=useState("");const [departmentId,setDepartmentId]=useState("");const [departmentSearch,setDepartmentSearch]=useState("");const [departmentOpen,setDepartmentOpen]=useState(false);
 const [evalFrom,setEvalFrom]=useState(cm.from);const [evalTo,setEvalTo]=useState(cm.to);const [evalRoom,setEvalRoom]=useState("");const [evalPreparer,setEvalPreparer]=useState("");
 const [data,setData]=useState<Data|null>(null);const [loading,setLoading]=useState(true);const [tab,setTab]=useState("overview");
 const load=useCallback(async(mode=tab)=>{setLoading(true);const q=new URLSearchParams();const f=mode==="evaluation"?evalFrom:from;const t=mode==="evaluation"?evalTo:to;const rId=mode==="evaluation"?evalRoom:roomId;if(f)q.set("from",f);if(t)q.set("to",t);if(rId)q.set("roomId",rId);if(mode!=="evaluation"&&departmentId)q.set("departmentId",departmentId);if(mode==="evaluation"&&evalPreparer)q.set("preparedById",evalPreparer);try{const r=await fetch("/mycar/api/v1/meeting-bookings/reports?"+q.toString(),{cache:"no-store"});const d=await r.json();if(r.ok)setData(d)}finally{setLoading(false)}},[tab,evalFrom,evalTo,evalRoom,evalPreparer,from,to,roomId,departmentId]);
 useEffect(()=>{let cancelled=false;const run=async()=>{await Promise.resolve();if(!cancelled)await load(tab)};void run();return()=>{cancelled=true}},[load,tab]);
 const exportRows=():ExportRow[]=>data?.bookings?.map((b:MeetingReportRow)=>({วันที่:fmt(b.startAt),ห้อง:b.room,หน่วยงาน:b.department,ผู้ขอ:b.requester,หัวข้อ:b.title,สถานะ:status(b.status ?? ""),เหตุผลยกเลิก:b.cancellationReason||"",ผู้ดูแล:b.preparedBy,สถานะเตรียมห้อง:b.preparationStatus,คะแนนประเมิน:b.evaluation??""}))||[];
 const exportXlsx=()=>{const rows=exportRows();if(!rows.length)return;const ws=XLSX.utils.json_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"รายงาน");XLSX.writeFile(wb,"รายงานระบบจองห้องประชุม.xlsx")};
 const exportPdf=async()=>{const rows=exportRows();if(!rows.length)return;const pdf=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"});try{const font=await fetch("/fonts/NotoSansThai-Regular.ttf").then(r=>r.arrayBuffer());let binary="";const bytes=new Uint8Array(font);for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));pdf.addFileToVFS("NotoSansThai-Regular.ttf",btoa(binary));pdf.addFont("NotoSansThai-Regular.ttf","NotoThai","normal");pdf.setFont("NotoThai")}catch{}pdf.setFontSize(14);pdf.text("รายงานระบบจองห้องประชุม",14,12);autoTable(pdf,{startY:17,head:[["วันที่","ห้อง","หน่วยงาน","ผู้ขอ","หัวข้อ","สถานะ","เหตุผลยกเลิก"]],body:rows.map((r:ExportRow)=>Object.values(r).slice(0,7).map(v=>String(v??""))),styles:{fontSize:7},margin:{left:10,right:10}});pdf.save("รายงานระบบจองห้องประชุม.pdf")};
 const exportCsv=()=>{const rows=exportRows();if(!rows.length)return;const ws=XLSX.utils.json_to_sheet(rows);const csv=XLSX.utils.sheet_to_csv(ws);const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download="meeting-room-report.csv";a.click();URL.revokeObjectURL(a.href)};
 const s=data?.summary||{};const maxRoom=Math.max(...(data?.rooms||[]).map((x:MeetingReportRow)=>x.bookings ?? 0),1);const maxDept=Math.max(...(data?.departments||[]).map((x:MeetingReportRow)=>x.bookings ?? 0),1);
 const tabs=[{id:"overview",label:"ภาพรวม",icon:<BarChart3 size={17}/>},{id:"bookings",label:"การจอง",icon:<CalendarDays size={17}/>},{id:"usage",label:"การใช้ห้อง",icon:<Building2 size={17}/>},{id:"people",label:"ผู้ใช้งานและอนุมัติ",icon:<UserRound size={17}/>},{id:"evaluation",label:"การประเมิน",icon:<Star size={17}/>},{id:"workload",label:"ภาระงานดูแลห้อง",icon:<ShieldCheck size={17}/>},{id:"resources",label:"อุปกรณ์และเหตุผล",icon:<Boxes size={17}/>}];
 return <section className="space-y-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-bold tracking-[0.14em] text-teal-700">MEETING REPORTS</p><h1 className="mt-1 text-3xl font-black text-slate-900">รายงานระบบจองห้องประชุม</h1><p className="mt-2 text-sm text-slate-500">รายงานการจอง การใช้ห้อง ผู้ใช้งาน การประเมิน และภาระงานดูแลห้อง</p></div><div className="flex flex-wrap gap-2"><button onClick={exportXlsx} className="inline-flex items-center gap-2 rounded-xl border border-green-200 bg-green-50 px-4 py-2.5 text-sm font-bold text-green-700"><FileSpreadsheet size={17}/>Excel</button><button onClick={exportPdf} className="inline-flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 px-4 py-2.5 text-sm font-bold text-red-700"><FileText size={17}/>PDF</button><button onClick={exportCsv} className="inline-flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2.5 text-sm font-bold text-emerald-700"><Download size={17}/>CSV</button><button onClick={()=>load()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700"><RefreshCw size={17}/>รีเฟรช</button></div></div>
 {tab!=="evaluation"&&<div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2 font-black text-slate-800"><Filter size={18} className="text-teal-600"/>ตัวกรองรายงาน</div><div className="grid gap-3 md:grid-cols-4"><label className="text-sm font-bold text-slate-600">ตั้งแต่วันที่<DatePicker value={from} onChange={setFrom}/></label><label className="text-sm font-bold text-slate-600">ถึงวันที่<DatePicker value={to} onChange={setTo}/></label><label className="text-sm font-bold text-slate-600">ห้องประชุม<select value={roomId} onChange={e=>setRoomId(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-2.5"><option value="">ทั้งหมด</option>{data?.masters?.rooms?.map((x:MasterRow)=><option key={x.publicId} value={x.publicId}>{x.nameTh}</option>)}</select></label><div className="relative text-sm font-bold text-slate-600"><span>หน่วยงาน</span><button type="button" onClick={()=>setDepartmentOpen(v=>!v)} className="mt-2 flex w-full items-center justify-between rounded-xl border border-slate-200 bg-white p-2.5 text-left font-normal"><span>{data?.masters?.departments?.find((x:MasterRow)=>x.publicId===departmentId)?.nameTh||"ทั้งหมด"}</span><ChevronDown size={16}/></button>{departmentOpen&&<div className="absolute z-20 mt-1 w-full rounded-xl border border-slate-200 bg-white p-2 shadow-xl"><div className="flex items-center gap-2 rounded-lg border p-2"><Search size={15}/><input autoFocus value={departmentSearch} onChange={e=>setDepartmentSearch(e.target.value)} placeholder="ค้นหาหน่วยงาน..." className="w-full outline-none"/></div><button onClick={()=>{setDepartmentId("");setDepartmentOpen(false)}} className="mt-1 w-full rounded-lg px-3 py-2 text-left hover:bg-slate-50">ทั้งหมด</button>{data?.masters?.departments?.filter((x:MasterRow)=>x.nameTh.toLowerCase().includes(departmentSearch.toLowerCase())).map((x:MasterRow)=><button key={x.publicId} onClick={()=>{setDepartmentId(x.publicId);setDepartmentOpen(false);setDepartmentSearch("")}} className="block w-full rounded-lg px-3 py-2 text-left hover:bg-teal-50">{x.nameTh}</button>)}</div>}</div></div><div className="mt-3 flex items-center justify-between"><span className="text-xs text-slate-400">รูปแบบวันที่: dd/mm/yyyy</span><button onClick={()=>load()} className="rounded-xl bg-teal-600 px-5 py-2.5 text-sm font-bold text-white">เรียกดูรายงาน</button></div></div>}
 <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white p-1 shadow-sm"><div className="flex min-w-max gap-1">{tabs.map(t=><button key={t.id} onClick={()=>setTab(t.id)} className={`inline-flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-bold ${tab===t.id?"bg-teal-600 text-white":"text-slate-600 hover:bg-slate-100"}`}>{t.icon}{t.label}</button>)}</div></div>
 {loading?<div className="rounded-3xl bg-white p-12 text-center text-slate-500">กำลังโหลดรายงาน…</div>:data&&<div className="space-y-5">
 {tab==="overview"&&<><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><K icon={<ClipboardCheck/>} label="การจองทั้งหมด" value={s.total??0}/><K icon={<DoorOpen/>} label="ชั่วโมงการใช้ห้อง" value={Number(s.usedHours||0).toFixed(2)}/><K icon={<Star/>} label="คะแนนเฉลี่ย" value={`${s.avgOverall??0} / 5`}/><K icon={<UsersRound/>} label="ตอบแบบประเมิน" value={`${s.evaluationCount??0} รายการ`}/></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[["รออนุมัติ",s.pending],["อนุมัติแล้ว",s.approved],["เสร็จสิ้น",s.completed],["ปฏิเสธ",s.rejected],["ยกเลิก",s.cancelled]].map(([l,v])=><K key={String(l)} label={String(l)} value={v??0}/>)}</div><div className="grid gap-5 lg:grid-cols-2"><Panel title="แนวโน้มการจองรายเดือน"><Bars rows={data.trend||[]} max={Math.max(...(data.trend||[]).map((x:MeetingReportRow)=>x.bookings ?? 0),1)} value="bookings" suffix="ครั้ง"/></Panel><Panel title="ช่วงเวลาเริ่มประชุม"><Bars rows={(data.peakHours||[]).map((x:MeetingReportRow)=>({name:`${String(x.hour).padStart(2,"0")}:00 น.`,...x}))} max={Math.max(...(data.peakHours||[]).map((x:MeetingReportRow)=>x.count ?? 0),1)} value="count" suffix="ครั้ง"/></Panel></div></>}
 {tab==="bookings"&&<><Panel title="สรุปสถานะการจอง"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5 mt-4">{[["รออนุมัติ",s.pending],["อนุมัติแล้ว",s.approved],["เสร็จสิ้น",s.completed],["ปฏิเสธ",s.rejected],["ยกเลิก",s.cancelled]].map(([l,v])=><K key={String(l)} label={String(l)} value={v??0}/>)}</div></Panel><Panel title="รายการจองรายละเอียด"><Table headers={["วันที่","ห้อง","หน่วยงาน","ผู้ขอ","หัวข้อ","สถานะ","เหตุผลยกเลิก","ผู้ดูแล"]}>{(data.bookings||[]).map((b:MeetingReportRow)=><tr key={b.publicId}><td className="p-3 whitespace-nowrap">{fmt(b.startAt)}</td><td className="p-3">{b.room}</td><td className="p-3">{b.department}</td><td className="p-3">{b.requester}</td><td className="p-3">{b.title}</td><td className="p-3 font-bold">{status(b.status ?? "")}</td><td className="p-3">{b.cancellationReason||"-"}</td><td className="p-3">{b.preparedBy||"-"}</td></tr>)}</Table></Panel></>}
 {tab==="usage"&&<><div className="grid gap-5 lg:grid-cols-2"><Panel title="การใช้ห้องประชุมรายห้อง"><Bars rows={data.rooms||[]} max={maxRoom} suffix="ครั้ง" value="bookings"/></Panel><Panel title="การจองแยกตามหน่วยงาน"><Bars rows={data.departments||[]} max={maxDept} suffix="ครั้ง" value="bookings"/></Panel></div><Panel title="รายละเอียดการใช้ห้อง"><Table headers={["ห้อง","จำนวนการจอง","ชั่วโมง","ผู้เข้าร่วม","เสร็จสิ้น","ความจุ"]}>{(data.rooms||[]).map((x:MeetingReportRow)=><tr key={x.name}><td className="p-3 font-bold">{x.name}</td><td className="p-3">{x.bookings}</td><td className="p-3">{x.hours}</td><td className="p-3">{x.attendees}</td><td className="p-3">{x.completed}</td><td className="p-3">{x.capacity}</td></tr>)}</Table></Panel></>}
 {tab==="people"&&<><Panel title="ผู้ขอใช้ห้องประชุม"><Table headers={["ผู้ขอ","จำนวนครั้ง","ชั่วโมง","เสร็จสิ้น","ยกเลิก","ประเมิน"]}>{(data.requesters||[]).map((x:MeetingReportRow)=><tr key={x.id}><td className="p-3 font-bold">{x.name}</td><td className="p-3">{x.bookings}</td><td className="p-3">{x.hours}</td><td className="p-3">{x.completed}</td><td className="p-3">{x.cancelled}</td><td className="p-3">{x.evaluated}</td></tr>)}</Table></Panel><Panel title="ผู้อนุมัติการจอง"><Table headers={["ผู้อนุมัติ","อนุมัติ","เสร็จสิ้น","ยกเลิก","เฉลี่ยตัดสินใจ"]}>{(data.approvers||[]).map((x:MeetingReportRow)=><tr key={x.id}><td className="p-3 font-bold">{x.name}</td><td className="p-3">{x.approved}</td><td className="p-3">{x.completed}</td><td className="p-3">{x.cancelled}</td><td className="p-3">{x.avgDecisionHours} ชม.</td></tr>)}</Table></Panel></>}
 {tab==="evaluation"&&<><Panel title="ตัวกรองผลประเมินความพึงพอใจ"><div className="grid gap-3 md:grid-cols-3"><label className="text-sm font-bold text-slate-600">ตั้งแต่วันที่<DatePicker value={evalFrom} onChange={setEvalFrom}/></label><label className="text-sm font-bold text-slate-600">ถึงวันที่<DatePicker value={evalTo} onChange={setEvalTo} min={evalFrom||undefined}/></label><label className="text-sm font-bold text-slate-600">ห้องประชุม<select value={evalRoom} onChange={e=>setEvalRoom(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-2.5"><option value="">ทั้งหมด</option>{data?.masters?.rooms?.map((x:MasterRow)=><option key={x.publicId} value={x.publicId}>{x.nameTh}</option>)}</select></label></div><div className="mt-3 grid gap-3 md:grid-cols-[1fr_auto] items-end"><label className="text-sm font-bold text-slate-600">ชื่อผู้จัดเตรียมห้องประชุม<select value={evalPreparer} onChange={e=>setEvalPreparer(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-2.5"><option value="">ทั้งหมด</option>{data?.masters?.preparers?.map((x:MasterRow)=><option key={x.publicId} value={x.publicId}>{userName(x)}</option>)}</select></label><button onClick={()=>load("evaluation")} className="rounded-xl bg-teal-600 px-5 py-2.5 text-sm font-bold text-white">เรียกดูผลประเมิน</button></div><p className="mt-3 text-xs text-slate-400">ค่าเริ่มต้น: เดือนปัจจุบัน</p></Panel><Panel title="ผลประเมินความพึงพอใจ"><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["โดยรวม",s.avgOverall],["อุปกรณ์",s.avgEquipment],["ความสะอาด",s.avgCleanliness],["การบริการ",s.avgFacilitation],["ความเหมาะสม",s.avgSuitability]].map(([l,v])=><K key={String(l)} label={String(l)} value={`${v??0} / 5`}/>)}</div><h3 className="mt-6 font-black">ปัญหาที่ถูกรายงาน</h3><div className="mt-3 flex flex-wrap gap-2">{(data.issues||[]).length?(data.issues||[]).map((x:MeetingReportRow)=><span key={x.name} className="rounded-full bg-rose-50 px-3 py-1.5 text-sm font-bold text-rose-700">{x.name} {x.count} ครั้ง</span>):<span className="text-sm text-slate-400">ยังไม่มีการรายงานปัญหา</span>}</div></Panel><Panel title="สรุปการประเมินรายบุคคล"><Table headers={["ผู้ประเมิน","จำนวน","อุปกรณ์","ความสะอาด","บริการ","ความเหมาะสม","โดยรวม","ปัญหา","ล่าสุด"]}>{(data.individual||[]).map((x:MeetingReportRow)=><tr key={x.id}><td className="p-3 font-bold"><Link className="text-teal-700 hover:underline" href={`/portal/meeting-rooms/evaluation/individual/${x.id}`}>{x.name}</Link></td><td className="p-3">{x.count}</td><td className="p-3">{x.equipment}</td><td className="p-3">{x.cleanliness}</td><td className="p-3">{x.facilitation}</td><td className="p-3">{x.suitability}</td><td className="p-3 font-black text-amber-600">{x.overall}</td><td className="p-3">{x.issues}</td><td className="p-3">{fmt(x.last)}</td></tr>)}</Table></Panel></>}
 {tab==="workload"&&<><Panel title="ภาระงานการดูแลห้องประชุม"><Table headers={["ผู้ดูแล","ได้รับมอบหมาย","ยังไม่เริ่ม","กำลังเตรียม","พร้อมใช้งาน","เสร็จสิ้น","เตรียมล่วงหน้าเฉลี่ย (ชม.)"]}>{(data.workload||[]).map((x:MeetingReportRow)=><tr key={x.id}><td className="p-3 font-bold">{x.name}</td><td className="p-3">{x.assigned}</td><td className="p-3">{x.notStarted}</td><td className="p-3">{x.inProgress}</td><td className="p-3">{x.ready}</td><td className="p-3">{x.completed}</td><td className="p-3">{x.avgPreparationLeadHours}</td></tr>)}</Table></Panel></>}
 {tab==="resources"&&<><Panel title="การใช้อุปกรณ์"><Table headers={["รหัส","อุปกรณ์","จำนวนรายการจอง","จำนวนที่ขอ"]}>{(data.equipment||[]).map((x:MeetingReportRow)=><tr key={x.id}><td className="p-3">{x.code}</td><td className="p-3 font-bold">{x.name}</td><td className="p-3">{x.bookingCount}</td><td className="p-3">{x.quantity}</td></tr>)}</Table></Panel><Panel title="เหตุผลการปฏิเสธ"><Table headers={["เหตุผล","จำนวน"]}>{(data.rejectedReasons||[]).map((x:MeetingReportRow)=><tr key={x.reason}><td className="p-3">{x.reason}</td><td className="p-3 font-bold">{x.count}</td></tr>)}</Table></Panel></>}
 </div>}</section>;
}
function Table({headers,children}:{headers:string[],children:React.ReactNode}){return <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead className="bg-slate-50 text-left"><tr>{headers.map(h=><th key={h} className="p-3 font-bold text-slate-600">{h}</th>)}</tr></thead><tbody className="divide-y">{children}</tbody></table></div>}
function K({icon,label,value}:{icon?:React.ReactNode;label:string;value:React.ReactNode}){return <div className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-center gap-3">{icon&&<span className="text-teal-600">{icon}</span>}<div><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-2xl font-black text-slate-900">{value}</div></div></div></div>}
function Panel({title,children}:{title:string,children:React.ReactNode}){return <div className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-black text-slate-900">{title}</h2>{children}</div>}
function Bars({rows,max,suffix,value="count"}:{rows:MeetingReportRow[];max:number;suffix:string;value?:keyof MeetingReportRow}){return <div className="mt-4 space-y-3">{rows.slice(0,10).map((x:MeetingReportRow)=><div key={x.name}><div className="mb-1 flex justify-between text-sm"><span className="font-bold">{x.name}</span><span className="text-slate-500">{x[value]??0} {suffix}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-500" style={{width:`${Math.max(4,Number(x[value] ?? 0)/max*100)}%`}}/></div></div>)}{!rows.length&&<p className="py-6 text-sm text-slate-400">ยังไม่มีข้อมูล</p>}</div>}
