"use client";

import { FormEvent, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, CarFront, MapPin, Users, Clock3, FileText, X } from "lucide-react";

type EditableRequest = { publicId: string; status: string; departureDate: string; departureTime: string; returnDate: string; returnTime: string; destination: string; purpose: string; passengerCount: number; passengerNames: string | null; note: string | null };
type FormState = { date: string; departure: string; returnDate: string; returnTime: string; destination: string; purpose: string; passengerCount: string; passengerNames: string; note: string };
const emptyForm: FormState = { date: "", departure: "08:00", returnDate: "", returnTime: "17:00", destination: "", purpose: "", passengerCount: "1", passengerNames: "", note: "" };

export default function VehicleRequestForm({ displayName, departmentName, initialRequest }: { displayName: string; departmentName: string; initialRequest?: EditableRequest | null }) {
  const router = useRouter();
  const editing = Boolean(initialRequest);
  const [form, setForm] = useState<FormState>(initialRequest ? { date: initialRequest.departureDate, departure: initialRequest.departureTime, returnDate: initialRequest.returnDate, returnTime: initialRequest.returnTime, destination: initialRequest.destination, purpose: initialRequest.purpose, passengerCount: String(initialRequest.passengerCount), passengerNames: initialRequest.passengerNames ?? "", note: initialRequest.note ?? "" } : emptyForm);
  const [saving, setSaving] = useState(false);
  const [done, setDone] = useState(false);
  function set<K extends keyof FormState>(key: K, value: FormState[K]) { setForm((current) => ({ ...current, [key]: value })); }
  function cancelEdit() { router.push("/dashboard/vehicle-requests"); }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setDone(false);
    if (!form.date || !form.returnDate || !form.destination.trim() || !form.purpose.trim()) return alert("กรุณากรอกวันที่เดินทาง วันที่เดินทางกลับ จุดหมาย และวัตถุประสงค์");
    if (`${form.returnDate}T${form.returnTime}` <= `${form.date}T${form.departure}`) return alert("กรุณาตรวจสอบวันและเวลาออกเดินทาง/เดินทางกลับ");
    setSaving(true);
    try {
      const response = await fetch(editing ? `/mycar/api/v1/vehicle-requests/${initialRequest!.publicId}` : "/mycar/api/v1/vehicle-requests", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ departureDate: form.date, departureTime: form.departure, returnDate: form.returnDate, returnTime: form.returnTime, destination: form.destination, purpose: form.purpose, passengerCount: Number(form.passengerCount), passengerNames: form.passengerNames, note: form.note }) });
      const payload = await response.json();
      if (!response.ok) return alert(payload.error ?? (editing ? "ไม่สามารถแก้ไขคำขอได้" : "ไม่สามารถส่งคำขอได้"));
      if (editing) { router.push("/dashboard/vehicle-requests"); router.refresh(); return; }
      setForm(emptyForm); setDone(true); router.refresh();
    } catch { alert("ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ได้"); } finally { setSaving(false); }
  }
  return <form onSubmit={submit} className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm">
    <div className="border-b border-slate-100 bg-gradient-to-r from-teal-50 to-white px-5 py-5 sm:px-7"><div className="flex items-start gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-teal-600 text-white shadow-sm"><CarFront size={21} /></span><div><h2 className="font-black text-slate-900">{editing ? "แก้ไขคำขอใช้รถยนต์" : "แบบฟอร์มขอใช้รถยนต์"}</h2><p className="mt-1 text-xs text-slate-500">{editing ? "แก้ไขรายละเอียดคำขอ แล้วบันทึกการเปลี่ยนแปลง" : "ข้อมูลผู้ขอจะถูกดึงจากบัญชีที่เข้าสู่ระบบโดยอัตโนมัติ"}</p></div></div></div>
    <div className="grid gap-5 p-5 sm:p-7">
      <div className="grid gap-3 rounded-2xl bg-slate-50 p-4 sm:grid-cols-2"><Info label="ผู้ขอใช้รถ" value={displayName} /><Info label="หน่วยงาน / แผนก" value={departmentName} /></div>
      <div className="grid gap-5 md:grid-cols-4"><DateField label="วันที่เดินทาง" value={form.date} onChange={(value) => set("date", value)} /><TimeField label="เวลาออกเดินทาง" value={form.departure} onChange={(value) => set("departure", value)} /><DateField label="วันที่เดินทางกลับ" min={form.date || undefined} value={form.returnDate} onChange={(value) => set("returnDate", value)} /><TimeField label="เวลากลับโดยประมาณ" value={form.returnTime} onChange={(value) => set("returnTime", value)} /></div>
      <div className="grid gap-5 md:grid-cols-2"><Field label="จุดหมาย / สถานที่ไป" icon={MapPin}><input required value={form.destination} onChange={(e) => set("destination", e.target.value)} placeholder="เช่น โรงพยาบาลร้อยเอ็ด" className="input" /></Field><Field label="วัตถุประสงค์" icon={FileText}><input required value={form.purpose} onChange={(e) => set("purpose", e.target.value)} placeholder="เช่น ส่งผู้ป่วย / ประชุม / ราชการ" className="input" /></Field></div>
      <div className="grid gap-5 md:grid-cols-2"><Field label="จำนวนผู้โดยสาร" icon={Users}><input required min="1" max="100" type="number" value={form.passengerCount} onChange={(e) => set("passengerCount", e.target.value)} className="input" /></Field><Field label="รายชื่อผู้ร่วมเดินทาง (ถ้ามี)" icon={Users}><input value={form.passengerNames} onChange={(e) => set("passengerNames", e.target.value)} placeholder="คั่นแต่ละชื่อด้วย ," className="input" /></Field></div>
      <Field label="หมายเหตุเพิ่มเติม"><textarea value={form.note} onChange={(e) => set("note", e.target.value)} rows={3} placeholder="รายละเอียดที่เจ้าหน้าที่ควรทราบ เช่น สัมภาระ อุปกรณ์ หรือเงื่อนไขพิเศษ" className="input resize-none" /></Field>
      {done ? <div className="rounded-2xl bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">ส่งคำขอใช้รถเรียบร้อยแล้ว ฟอร์มถูกเคลียร์เรียบร้อย สถานะ: รอพิจารณา</div> : null}
      <div className="flex flex-wrap items-center justify-end gap-3 border-t border-slate-100 pt-5"><span className="mr-auto text-xs text-slate-400">{editing ? "การแก้ไขจะถูกบันทึกในประวัติการใช้งาน" : "หลังส่งคำขอ เจ้าหน้าที่จะจัดรถและพนักงานขับรถให้"}</span>{editing ? <button type="button" onClick={cancelEdit} disabled={saving} className="rounded-xl border border-slate-200 bg-white px-5 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-50"><X size={15} className="mr-1 inline" />ยกเลิกการแก้ไข</button> : null}<button type="submit" disabled={saving} className="rounded-xl bg-teal-600 px-5 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-teal-700 disabled:opacity-50">{saving ? "กำลังบันทึก..." : editing ? "บันทึกการแก้ไข" : "ส่งคำขอใช้รถ"}</button></div>
    </div>
  </form>;
}

function DateField({ label, value, min, onChange }: { label: string; value: string; min?: string; onChange: (value: string) => void }) { const ref = useRef<HTMLInputElement>(null); return <Field label={label} icon={CalendarDays}><div className="relative" onClick={() => { try { ref.current?.showPicker?.(); } catch { ref.current?.click(); } }}><input ref={ref} required type="date" min={min} value={value} onChange={(e) => onChange(e.target.value)} className="pointer-events-none absolute inset-0 h-full w-full opacity-0" aria-label={label} /><div className="input flex items-center justify-between bg-white"><span className={value ? "text-slate-700" : "text-slate-400"}>{value ? formatThaiDate(value) : "วัน / เดือน / พ.ศ."}</span><CalendarDays size={17} className="text-slate-400" /></div></div></Field>; }
function TimeField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { const [open, setOpen] = useState(false); const [hour, minute] = (value || "00:00").split(":"); const hours = Array.from({ length: 24 }, (_, index) => String(index).padStart(2, "0")); const minutes = Array.from({ length: 60 }, (_, index) => String(index).padStart(2, "0")); return <Field label={label} icon={Clock3}><div className="relative"><button type="button" onClick={() => setOpen((current) => !current)} className="input flex w-full items-center justify-between bg-white text-left"><span className="text-slate-700">{value || "00:00"} น.</span><Clock3 size={17} className="text-slate-400" /></button>{open ? <div className="absolute left-0 right-0 top-[calc(100%+6px)] z-30 rounded-2xl border border-slate-200 bg-white p-3 shadow-xl"><div className="mb-2 text-xs font-bold text-slate-500">เลือกเวลาแบบ 24 ชั่วโมง</div><div className="grid grid-cols-2 gap-2"><select value={hour} onChange={(e) => onChange(`${e.target.value}:${minute}`)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold outline-none focus:border-teal-500" aria-label="ชั่วโมง">{hours.map((item) => <option key={item} value={item}>{item}</option>)}</select><select value={minute} onChange={(e) => onChange(`${hour}:${e.target.value}`)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold outline-none focus:border-teal-500" aria-label="นาที">{minutes.map((item) => <option key={item} value={item}>{item}</option>)}</select></div><button type="button" onClick={() => setOpen(false)} className="mt-2 w-full rounded-xl bg-teal-600 px-3 py-2 text-sm font-bold text-white">ตกลง</button></div> : null}</div></Field>; }
function formatThaiDate(value: string) { const [year, month, day] = value.split("-").map(Number); return new Intl.DateTimeFormat("th-TH-u-ca-buddhist", { day: "2-digit", month: "long", year: "numeric" }).format(new Date(year, month - 1, day)); }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-[11px] font-bold text-slate-400">{label}</p><p className="mt-1 text-sm font-bold text-slate-700">{value}</p></div>; }
function Field({ label, icon: Icon, children }: { label: string; icon?: typeof MapPin; children: React.ReactNode }) { return <label className="block text-sm font-semibold text-slate-700"><span className="flex items-center gap-2">{Icon ? <Icon size={15} className="text-teal-600" /> : null}{label}</span><div className="mt-2">{children}</div></label>; }
