"use client";

import { useEffect, useState } from "react";
import { apiPath } from "@/lib/api-path";
import { Fuel, Info, Printer } from "lucide-react";

type ExpenseRow={publicId:string;departureDate:string;vehicle:string;driver:string;department:string;fuelLiters:number;fuelAmount:number;expenseAmount:number;totalAmount:number};
type ExpenseTotals={fuel:number;expenses:number;total:number;fuelLiters:number};
type ExpenseReport={rows:ExpenseRow[];totals:ExpenseTotals};

export default function ExpensesReportPage() {
  const [state, setState] = useState<ExpenseReport | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch(apiPath("/api/v1/reports/expenses"), { cache: "no-store" }).then((r) => r.json()).then(setState).finally(() => setLoading(false)); }, []);
  const rows = state?.rows ?? []; const totals = state?.totals ?? { fuel: 0, expenses: 0, total: 0, fuelLiters: 0 };
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-teal-700">เธฃเธฒเธขเธเธฒเธ</p><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-900">เธฃเธฒเธขเธเธฒเธเธเนเธฒเนเธเนเธเนเธฒเธข</h1><p className="mt-2 text-sm text-slate-500">เธชเธฃเธธเธเน€เธเธทเนเธญเน€เธเธฅเธดเธเนเธฅเธฐเธเนเธฒเนเธเนเธเนเธฒเธขเธเธฃเธดเธเธเธฒเธเธเธฑเธเธ—เธถเธเธเธฒเธฃเนเธเนเธฃเธ–</p></div><button onClick={()=>window.print()} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-bold print:hidden"><Printer size={17}/>เธเธดเธกเธเน / PDF</button></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="เธเนเธฒเน€เธเธทเนเธญเน€เธเธฅเธดเธ" value={totals.fuel}/><Metric label="เธเนเธฒเนเธเนเธเนเธฒเธขเธญเธทเนเธ" value={totals.expenses}/><Metric label="เธเนเธฒเนเธเนเธเนเธฒเธขเธฃเธงเธก" value={totals.total}/><Metric label="เน€เธเธทเนเธญเน€เธเธฅเธดเธเธฃเธงเธก" value={totals.fuelLiters} unit="เธฅเธดเธ•เธฃ"/></div>
    {loading ? <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">เธเธณเธฅเธฑเธเนเธซเธฅเธ”เธฃเธฒเธขเธเธฒเธโ€ฆ</div> : rows.length === 0 ? <section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><div className="flex gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-white text-amber-700"><Fuel size={20}/></span><div><h2 className="font-black text-amber-900">เธขเธฑเธเนเธกเนเธกเธตเธเธฑเธเธ—เธถเธเธเนเธฒเนเธเนเธเนเธฒเธข</h2><p className="mt-1 text-sm leading-6 text-amber-800">เน€เธกเธทเนเธญ เธเธเธฃ. เธเธฑเธเธ—เธถเธเธเนเธณเธกเธฑเธเธซเธฃเธทเธญเธเนเธฒเนเธเนเธเนเธฒเธขเน€เธเธดเนเธกเน€เธ•เธดเธก เธฃเธฐเธเธเธเธฐเธเธณเธเนเธญเธกเธนเธฅเธเธฃเธดเธเธกเธฒเนเธชเธ”เธเนเธเธฃเธฒเธขเธเธฒเธเธเธตเน</p></div></div></section> : <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3 text-left">เธงเธฑเธเธ—เธตเน</th><th className="px-4 py-3 text-left">เธฃเธ–</th><th className="px-4 py-3 text-left">เธเธเธฃ.</th><th className="px-4 py-3 text-left">เธซเธเนเธงเธขเธเธฒเธ</th><th className="px-4 py-3 text-right">เธฅเธดเธ•เธฃ</th><th className="px-4 py-3 text-right">เน€เธเธทเนเธญเน€เธเธฅเธดเธ</th><th className="px-4 py-3 text-right">เธเนเธฒเนเธเนเธเนเธฒเธขเธญเธทเนเธ</th><th className="px-4 py-3 text-right">เธฃเธงเธก</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((r:ExpenseRow)=><tr key={r.publicId}><td className="px-4 py-3">{new Intl.DateTimeFormat("th-TH-u-ca-buddhist",{dateStyle:"medium",timeZone:"Asia/Bangkok"}).format(new Date(r.departureDate))}</td><td className="px-4 py-3 font-semibold">{r.vehicle}</td><td className="px-4 py-3">{r.driver}</td><td className="px-4 py-3">{r.department}</td><td className="px-4 py-3 text-right">{r.fuelLiters.toLocaleString(undefined,{maximumFractionDigits:2})}</td><td className="px-4 py-3 text-right">{r.fuelAmount.toLocaleString(undefined,{minimumFractionDigits:2})}</td><td className="px-4 py-3 text-right">{r.expenseAmount.toLocaleString(undefined,{minimumFractionDigits:2})}</td><td className="px-4 py-3 text-right font-black">{r.totalAmount.toLocaleString(undefined,{minimumFractionDigits:2})}</td></tr>)}</tbody></table></div></div>}
    <div className="rounded-2xl border border-slate-200 bg-slate-50 p-5 text-sm text-slate-600"><Info size={17} className="mr-2 inline text-teal-600"/>เธ•เธฑเธงเน€เธฅเธเธฃเธฒเธขเธเธฒเธเธกเธฒเธเธฒเธเธฃเธฒเธขเธเธฒเธฃเธ—เธตเน เธเธเธฃ. เธเธฑเธเธ—เธถเธเธเธฃเธดเธ เนเธกเนเนเธเนเธเธฒเธฃเธเธฃเธฐเธกเธฒเธ“เธเนเธฒ</div>
  </div>;
}
function Metric({label,value,unit="เธเธฒเธ—"}:{label:string;value:number;unit?:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-slate-900">{value.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}</p><p className="mt-1 text-xs text-slate-400">{unit}</p></div>}


