"use client";

import { useEffect, useState } from "react";
import { FileSpreadsheet, Filter, Printer, RefreshCw, Search, X } from "lucide-react";
import DatePicker from "@/components/date-picker";

type FilterState = { from: string; to: string; status: string; departmentId: string; vehicleId: string; driverId: string };
type Master = { publicId: string; code?: string; nameTh?: string; licensePlate?: string | null; brand?: string | null; model?: string | null; firstName?: string; lastName?: string; nickname?: string | null };
type Row = { publicId:string; departureDate:string; destination:string; purpose:string; passengerCount:number; status:string; requester?:{nameTh?:string|null;firstnameTh?:string|null;lastnameTh?:string|null}|null; department?:{nameTh?:string|null}|null; vehicle?:{licensePlate?:string|null;brand?:string|null;model?:string|null}|null; driver?:{firstName?:string;lastName?:string}|null };
const emptyFilters: FilterState = { from: "", to: "", status: "", departmentId: "", vehicleId: "", driverId: "" };
const statuses = [["", "ทั้งหมด"], ["PENDING", "รอพิจารณา"], ["APPROVED", "อนุมัติ"], ["REJECTED", "ไม่อนุมัติ"], ["CANCELLED", "ยกเลิก"], ["COMPLETED", "เสร็จสิ้น"]];
const input = "mt-1 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-100";
const statusText: Record<string, string> = Object.fromEntries(statuses);

function displayDate(v: string) { return new Intl.DateTimeFormat("th-TH-u-ca-buddhist", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(v)); }
function displayPerson(r: Row) { return r.requester?.nameTh || [r.requester?.firstnameTh, r.requester?.lastnameTh].filter(Boolean).join(" ") || "ไม่ระบุ"; }
function displayVehicle(r: Row) { return r.vehicle ? [r.vehicle.licensePlate, r.vehicle.brand, r.vehicle.model].filter(Boolean).join(" • ") : "-"; }
function displayDriver(r: Row) { return r.driver ? [r.driver.firstName, r.driver.lastName].filter(Boolean).join(" ") : "-"; }

export default function VehicleRequestReportPage() {
  const [filters, setFilters] = useState(emptyFilters); const [departments,setDepartments]=useState<Master[]>([]); const [vehicles,setVehicles]=useState<Master[]>([]); const [drivers,setDrivers]=useState<Master[]>([]); const [rows,setRows]=useState<Row[]>([]); const [counts,setCounts]=useState<Record<string,number>>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  async function loadMasters(){ const r=await fetch("/mycar/api/v1/reports",{cache:"no-store"}); const d=await r.json(); if(!r.ok) throw new Error(d.error||"ไม่สามารถโหลดตัวกรองได้"); setDepartments(d.departments||[]);setVehicles(d.vehicles||[]);setDrivers(d.drivers||[]); }
  async function load(){ setLoading(true);setError("");try{const p=new URLSearchParams();Object.entries(filters).forEach(([k,v])=>{if(v)p.set(k,v)});const r=await fetch(`/mycar/api/v1/reports/vehicle-requests?${p}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"ไม่สามารถโหลดรายงานได้");setRows(d.rows||[]);setCounts(d.counts||{})}catch(e){setError(e instanceof Error?e.message:"ไม่สามารถโหลดรายงานได้")}finally{setLoading(false)}}
  useEffect(()=>{let cancelled=false;const run=async()=>{try{await loadMasters()}catch(e){if(!cancelled)setError(e instanceof Error?e.message:"ไม่สามารถโหลดตัวกรองได้")}};void run();return()=>{cancelled=true}},[]);
  useEffect(()=>{let cancelled=false;const run=async()=>{setLoading(true);setError("");try{const p=new URLSearchParams();Object.entries(filters).forEach(([k,v])=>{if(v)p.set(k,v)});const r=await fetch(`/mycar/api/v1/reports/vehicle-requests?${p}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"ไม่สามารถโหลดรายงานได้");if(!cancelled){setRows(d.rows||[]);setCounts(d.counts||{})}}catch(e){if(!cancelled)setError(e instanceof Error?e.message:"ไม่สามารถโหลดรายงานได้")}finally{if(!cancelled)setLoading(false)}};void run();return()=>{cancelled=true}},[filters]);
  function exportCsv(){ const cols=["วันที่เดินทาง","ผู้ขอ","หน่วยงาน","ปลายทาง","วัตถุประสงค์","รถ","พขร.","ผู้โดยสาร","สถานะ"]; const body=rows.map(r=>[displayDate(r.departureDate),displayPerson(r),r.department?.nameTh||"-",r.destination,r.purpose,displayVehicle(r),displayDriver(r),r.passengerCount,statusText[r.status]||r.status].map(v=>JSON.stringify(v??"")).join(","));const b=new Blob(["\ufeff"+cols.join(",")+"\n"+body.join("\n")],{type:"text/csv;charset=utf-8"});const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download="รายงานคำขอใช้รถ.csv";a.click();URL.revokeObjectURL(u)}
  return <div className="space-y-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold text-teal-700">รายงาน</p><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-900">รายงานคำขอใช้รถ</h1><p className="mt-2 text-sm text-slate-500">สรุปและค้นหารายการคำขอใช้รถตามช่วงวันที่ หน่วยงาน รถ พขร. และสถานะ</p></div><div className="flex flex-wrap gap-2 print:hidden"><button onClick={exportCsv} disabled={!rows.length} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-bold text-slate-700 disabled:opacity-50"><FileSpreadsheet size={17}/>ส่งออก CSV</button><button onClick={()=>window.print()} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-bold"><Printer size={17}/>พิมพ์ / PDF</button></div></div>
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm print:hidden"><div className="mb-4 flex items-center gap-2"><Filter size={17} className="text-teal-700"/><h2 className="font-black text-slate-900">ตัวกรองรายงาน</h2></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><label className="text-xs font-bold text-slate-600">ตั้งแต่วันที่<DatePicker value={filters.from} onChange={v=>setFilters({...filters,from:v})}/></label><label className="text-xs font-bold text-slate-600">ถึงวันที่<DatePicker value={filters.to} onChange={v=>setFilters({...filters,to:v})} min={filters.from||undefined}/></label><label className="text-xs font-bold text-slate-600">สถานะ<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})} className={input}>{statuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-xs font-bold text-slate-600">หน่วยงาน<select value={filters.departmentId} onChange={e=>setFilters({...filters,departmentId:e.target.value})} className={input}><option value="">ทั้งหมด</option>{departments.map(d=><option key={d.publicId} value={d.publicId}>{d.code ? `${d.code} — ` : ""}{d.nameTh}</option>)}</select></label><label className="text-xs font-bold text-slate-600">รถยนต์<select value={filters.vehicleId} onChange={e=>setFilters({...filters,vehicleId:e.target.value})} className={input}><option value="">ทั้งหมด</option>{vehicles.map(v=><option key={v.publicId} value={v.publicId}>{[v.licensePlate,v.brand,v.model].filter(Boolean).join(" • ")||"ไม่ระบุ"}</option>)}</select></label><label className="text-xs font-bold text-slate-600">พนักงานขับรถ<select value={filters.driverId} onChange={e=>setFilters({...filters,driverId:e.target.value})} className={input}><option value="">ทั้งหมด</option>{drivers.map(d=><option key={d.publicId} value={d.publicId}>{d.firstName} {d.lastName}{d.nickname?` (${d.nickname})`:""}</option>)}</select></label></div><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setFilters(emptyFilters)} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 px-4 text-sm font-bold"><X size={16}/>ล้างตัวกรอง</button><button onClick={load} disabled={loading} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-teal-600 px-5 text-sm font-bold text-white disabled:opacity-50"><Search size={17}/>{loading?"กำลังค้นหา…":"ค้นหารายงาน"}</button></div></section>
  {error?<div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>:null}
  <section className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["ทั้งหมด",counts.total||0,"text-slate-900"],["รอพิจารณา",counts.PENDING||0,"text-amber-700"],["อนุมัติ",counts.APPROVED||0,"text-emerald-700"],["ไม่อนุมัติ",counts.REJECTED||0,"text-rose-700"],["ยกเลิก",counts.CANCELLED||0,"text-slate-600"],["เสร็จสิ้น",counts.COMPLETED||0,"text-blue-700"]].map(([l,n,c])=><div key={String(l)} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-[11px] font-bold text-slate-500">{l}</p><p className={`mt-1 text-2xl font-black ${c}`}>{n}</p></div>)}</section>
  <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-black text-slate-900">รายละเอียดคำขอใช้รถ</h2><p className="mt-1 text-xs text-slate-500">พบ {rows.length.toLocaleString("th-TH")} รายการ</p></div><button onClick={load} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-slate-200 px-3 text-xs font-bold print:hidden"><RefreshCw size={14}/>รีเฟรช</button></div><div className="overflow-x-auto"><table className="min-w-[1150px] w-full text-sm"><thead className="bg-slate-50 text-xs font-bold text-slate-600"><tr><th className="px-4 py-3 text-left">วันที่เดินทาง</th><th className="px-4 py-3 text-left">ผู้ขอ</th><th className="px-4 py-3 text-left">หน่วยงาน</th><th className="px-4 py-3 text-left">ปลายทาง</th><th className="px-4 py-3 text-left">วัตถุประสงค์</th><th className="px-4 py-3 text-left">รถ</th><th className="px-4 py-3 text-left">พขร.</th><th className="px-4 py-3 text-center">ผู้โดยสาร</th><th className="px-4 py-3 text-center">สถานะ</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((r:Row)=><tr key={r.publicId} className="hover:bg-slate-50"><td className="whitespace-nowrap px-4 py-3">{displayDate(r.departureDate)}</td><td className="px-4 py-3 font-semibold">{displayPerson(r)}</td><td className="px-4 py-3">{r.department?.nameTh||"-"}</td><td className="max-w-[220px] px-4 py-3">{r.destination}</td><td className="max-w-[240px] px-4 py-3">{r.purpose}</td><td className="px-4 py-3">{displayVehicle(r)}</td><td className="px-4 py-3">{displayDriver(r)}</td><td className="px-4 py-3 text-center">{r.passengerCount}</td><td className="px-4 py-3 text-center"><span className="inline-flex rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-bold text-slate-700">{statusText[r.status]||r.status}</span></td></tr>)}{!loading&&!rows.length?<tr><td colSpan={9} className="px-4 py-12 text-center text-sm text-slate-500">ไม่พบข้อมูลตามเงื่อนไข</td></tr>:null}</tbody></table></div></section></div>;
}
