function bangkokDateIso() { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Bangkok", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()); }
import { NextResponse } from "next/server";
import { getCurrentUser } from "@/modules/identity/session";
import { prisma } from "@/lib/prisma";
import { hasApplicationAccess } from "@/modules/portal/applications";
import { hasPermission } from "@/lib/authorization";
import { createMeetingBookingNotification, sendMophNotifyMeetingEvent, buildMeetingNotificationMessage } from "@/lib/notifications";
import { createMeetingPublicUrl, getPublicOrigin } from "@/lib/meeting-public-link";
function getRequesterName(user: { nameTh: string | null; firstnameTh: string | null; lastnameTh: string | null }) { return user.nameTh?.trim() || [user.firstnameTh, user.lastnameTh].filter(Boolean).join(" ").trim() || null; }
export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) { const user = await getCurrentUser(); if (!user) return NextResponse.json({ error: "UNAUTHORIZED" }, { status: 401 }); const hasAccess = await hasApplicationAccess(user.id, "MEETING_ROOMS"); const canManage = await hasPermission(user.id, "MANAGE_MEETING_BOOKINGS"); const canApprove = user.roles.some(({role})=>["SUPER_ADMIN","ADMIN"].includes(role.key)) || await hasPermission(user.id,"APPROVE_MEETING_BOOKINGS"); if (!hasAccess && !canManage && !canApprove) return NextResponse.json({ error: "FORBIDDEN" }, { status: 403 }); const { id } = await params; const booking = await prisma.meetingBooking.findFirst({ where: canManage || canApprove ? { publicId: id } : { publicId: id, requesterId: user.id }, include: { room: { select: { publicId: true, nameTh: true, location: true, capacity: true } }, equipment: { include: { equipment: { select: { publicId: true, nameTh: true } } } } } }); if (!booking) return NextResponse.json({ error: "ไม่พบรายการจอง" }, { status: 404 }); return NextResponse.json({ booking }); }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const user = await getCurrentUser(); if (!user) return NextResponse.json({ error: "UNAUTHORIZED" }, { status: 401 }); const { id } = await params; const canManage = await hasPermission(user.id,"MANAGE_MEETING_BOOKINGS"); const canApprove = user.roles.some(({role})=>["SUPER_ADMIN","ADMIN"].includes(role.key)) || await hasPermission(user.id,"APPROVE_MEETING_BOOKINGS");
  const existing = await prisma.meetingBooking.findFirst({ where: canManage || canApprove ? { publicId: id } : { publicId: id, requesterId: user.id }, select: { id: true, publicId: true, roomId: true, requesterId: true, status: true } }); if (!existing) return NextResponse.json({ error: "ไม่พบรายการจอง" }, { status: 404 });
  const isApprovedManagerEdit = existing.status === "APPROVED" && canApprove;
  if (existing.status !== "PENDING" && !isApprovedManagerEdit) return NextResponse.json({ error: "รายการที่อนุมัติแล้ว แก้ไขได้เฉพาะผู้มีสิทธิ์จัดการสถานะห้องประชุม" }, { status: 403 });
  const body = await request.json(); const todayIso = bangkokDateIso(); const startDatePart = String(body.startAt || "").slice(0, 10); const endDatePart = String(body.endAt || "").slice(0, 10); if (!/^\d{4}-\d{2}-\d{2}$/.test(startDatePart) || startDatePart < todayIso || !/^\d{4}-\d{2}-\d{2}$/.test(endDatePart) || endDatePart < todayIso) return NextResponse.json({ error: "ไม่สามารถบันทึกการจองในวันที่ผ่านมาแล้วได้ กรุณาเลือกวันที่ตั้งแต่วันนี้เป็นต้นไป" }, { status: 400 }); const roomPublicId = String(body.roomId || ""); const title = String(body.title || "").trim(); const purpose = body.purpose ? String(body.purpose) : null; const attendeeRaw = String(body.attendeeCount ?? "").trim(); const attendeeCount = Number(attendeeRaw); const startAt = new Date(body.startAt); const endAt = new Date(body.endAt); if (!roomPublicId || !title || !/^\d+$/.test(attendeeRaw) || !Number.isInteger(attendeeCount) || attendeeCount < 1 || Number.isNaN(startAt.getTime()) || Number.isNaN(endAt.getTime()) || endAt <= startAt) return NextResponse.json({ error: "ข้อมูลการจองไม่ถูกต้อง" }, { status: 400 });
  const room = await prisma.meetingRoom.findFirst({ where: { publicId: roomPublicId, status: "ACTIVE", deletedAt: null }, select: { id: true, publicId: true, nameTh: true, capacity: true } }); if (!room) return NextResponse.json({ error: "ไม่พบห้องประชุม" }, { status: 404 }); if (attendeeCount > room.capacity) return NextResponse.json({ error: `จำนวนผู้เข้าร่วมเกินความจุห้อง (${room.capacity} คน)` }, { status: 400 }); const overlap = await prisma.meetingBooking.findFirst({ where: { id: { not: existing.id }, roomId: room.id, status: { in: ["PENDING", "APPROVED"] }, startAt: { lt: endAt }, endAt: { gt: startAt } }, select: { publicId: true } }); if (overlap) return NextResponse.json({ error: "ช่วงเวลานี้มีการจองห้องแล้ว" }, { status: 409 });
  const equipmentIds = Array.isArray(body.equipmentIds) ? body.equipmentIds.map(String) : []; const equipment = equipmentIds.length ? await prisma.meetingEquipment.findMany({ where: { publicId: { in: equipmentIds }, status: "ACTIVE" }, select: { id: true } }) : [];
  const booking = await prisma.$transaction(async (tx) => { await tx.meetingBookingEquipment.deleteMany({ where: { bookingId: existing.id } }); return tx.meetingBooking.update({ where: { id: existing.id }, data: { roomId: room.id, title, purpose, attendeeCount, startAt, endAt, status: existing.status, ...(isApprovedManagerEdit ? { preparationStatus: "NOT_STARTED", preparedAt: null, preparedById: user.id } : {}), updatedAt: new Date(), equipment: { create: equipment.map((item) => ({ equipmentId: item.id, quantity: 1 })) } }, select: { id: true, publicId: true, status: true } }); });
  const requester = await prisma.user.findUnique({ where: { id: existing.requesterId }, select: { nameTh: true, firstnameTh: true, lastnameTh: true, department: { select: { nameTh: true } } } }); const requesterName = getRequesterName(requester ?? { nameTh: null, firstnameTh: null, lastnameTh: null }); const departmentName = requester?.department?.nameTh ?? null; const detailUrl = createMeetingPublicUrl(booking.publicId, getPublicOrigin(request)); const notificationInput = { requesterId: existing.requesterId, bookingId: booking.id, publicId: booking.publicId, roomName: room.nameTh, title, startAt, endAt, status: booking.status, eventType: "MEETING_BOOKING_UPDATED" as const, requesterName, departmentName, detailUrl }; const message = buildMeetingNotificationMessage(notificationInput); try { await createMeetingBookingNotification(notificationInput); } catch (error) { console.error("IN_APP meeting update notification failed", error); } try { const notifyResult = await sendMophNotifyMeetingEvent({ requesterId: existing.requesterId, publicId: booking.publicId, eventType: "MEETING_BOOKING_UPDATED", message, detailUrl }); console.info("MOPH Notify update booking result", notifyResult); } catch (error) { console.error("MOPH Notify update booking failed", error); } await prisma.auditLog.create({ data: { userId: user.id, action: "EDIT_MEETING_BOOKING", resource: "MEETING_BOOKING", resourceId: booking.publicId, result: "SUCCESS", metadata: { wasApproved: isApprovedManagerEdit } } }); return NextResponse.json({ booking });
}
export async function DELETE(request: Request, { params }: { params: Promise<{ id: string }> }) { const user = await getCurrentUser(); if (!user) return NextResponse.json({ error: "UNAUTHORIZED" }, { status: 401 }); const { id } = await params; const body = await request.json().catch(() => ({})); const cancellationReason = body?.reason ? String(body.reason).trim() : ""; const booking = await prisma.meetingBooking.findUnique({ where: { publicId: id }, include: { room: { select: { nameTh: true } }, requester: { select: { nameTh: true, firstnameTh: true, lastnameTh: true, department: { select: { nameTh: true } } } } } }); if (!booking) return NextResponse.json({ error: "ไม่พบรายการจอง" }, { status: 404 }); const isOwner = booking.requesterId === user.id; const canManage = await hasPermission(user.id, "MANAGE_MEETING_BOOKINGS"); if (!isOwner && !canManage) return NextResponse.json({ error: "FORBIDDEN" }, { status: 403 }); if (!["PENDING", "APPROVED"].includes(booking.status)) return NextResponse.json({ error: "รายการนี้ไม่สามารถยกเลิกได้" }, { status: 409 }); if (!cancellationReason) return NextResponse.json({ error: "กรุณาระบุเหตุผลการยกเลิก" }, { status: 400 }); const updated = await prisma.meetingBooking.update({ where: { id: booking.id }, data: { status: "CANCELLED", cancellationReason, cancelledAt: new Date(), updatedAt: new Date() }, select: { id: true, publicId: true, status: true, startAt: true, endAt: true } }); const detailUrl = createMeetingPublicUrl(booking.publicId, getPublicOrigin(request)); const notificationInput = { requesterId: booking.requesterId, bookingId: booking.id, publicId: booking.publicId, roomName: booking.room.nameTh, title: booking.title, startAt: booking.startAt, endAt: booking.endAt, status: updated.status, eventType: "MEETING_BOOKING_CANCELLED" as const, requesterName: getRequesterName(booking.requester), departmentName: booking.requester.department?.nameTh ?? null, detailUrl }; const message = buildMeetingNotificationMessage(notificationInput); try { await createMeetingBookingNotification(notificationInput); } catch (error) { console.error("IN_APP meeting cancellation notification failed", error); } try { await sendMophNotifyMeetingEvent({ requesterId: booking.requesterId, publicId: booking.publicId, eventType: "MEETING_BOOKING_CANCELLED", message, detailUrl }); } catch (error) { console.error("MOPH Notify cancel booking failed", error); } await prisma.auditLog.create({ data: { userId: user.id, action: "CANCEL_MEETING_BOOKING", resource: "MEETING_BOOKING", resourceId: booking.publicId, result: "SUCCESS", metadata: { owner: isOwner, cancellationReason } } }); return NextResponse.json({ booking: updated }); }
