"use client";

import { useCallback, useEffect, useState } from "react";
import { FileSpreadsheet, Filter, Printer, RefreshCw, X } from "lucide-react";
import DatePicker from "@/components/date-picker";

const input = "mt-1 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-100";
type AuditRow = { publicId?: string; id?: string; createdAt: string; action: string; resource: string; result: string; resourceId?: string | null; user?: { nameTh?: string | null; firstnameTh?: string | null; lastnameTh?: string | null } | null };
const results: Record<string,string> = { SUCCESS: "สำเร็จ", FAILURE: "ล้มเหลว", DENIED: "ถูกปฏิเสธ" };

export default function AuditReportPage() {
  const [from,setFrom]=useState(""); const [to,setTo]=useState(""); const [resource,setResource]=useState(""); const [result,setResult]=useState(""); const [rows,setRows]=useState<AuditRow[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const p=new URLSearchParams();Object.entries({from,to,resource,result,limit:"500"}).forEach(([k,v])=>{if(v)p.set(k,v)});const r=await fetch(`/mycar/api/v1/reports/audit?${p}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"ไม่สามารถโหลดรายงานได้");setRows(d.rows||[])}catch(e){setError(e instanceof Error?e.message:"ไม่สามารถโหลดรายงานได้")}finally{setLoading(false)}},[from,to,resource,result]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  const csv=()=>{const lines=["วันที่,ผู้ใช้งาน,การดำเนินการ,ทรัพยากร,ผลลัพธ์,รหัสอ้างอิง",...rows.map(r=>[new Date(r.createdAt).toLocaleString("th-TH-u-ca-buddhist"),r.user?.nameTh||[r.user?.firstnameTh,r.user?.lastnameTh].filter(Boolean).join(" ")||"ไม่ระบุ",r.action,r.resource,results[r.result]||r.result,r.resourceId||""].map(v=>JSON.stringify(v??"")).join(","))];const b=new Blob(["\ufeff"+lines.join("\n")],{type:"text/csv;charset=utf-8"});const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download="รายงานตรวจสอบ-Audit-Log.csv";a.click();URL.revokeObjectURL(u)};
  const reset=()=>{setFrom("");setTo("");setResource("");setResult("")};
  return <div className="space-y-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold text-teal-700">รายงานตรวจสอบ</p><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-900">รายงานประวัติการดำเนินการ</h1><p className="mt-2 text-sm text-slate-500">ตรวจสอบ Audit Log ของระบบตามช่วงเวลา ทรัพยากร และผลการดำเนินการ</p></div><div className="flex gap-2 print:hidden"><button onClick={csv} disabled={!rows.length} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-bold disabled:opacity-50"><FileSpreadsheet size={17}/>ส่งออก CSV</button><button onClick={()=>window.print()} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-bold"><Printer size={17}/>พิมพ์ / PDF</button></div></div>
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm print:hidden"><div className="mb-4 flex items-center gap-2"><Filter size={17} className="text-teal-700"/><h2 className="font-black">ตัวกรองรายงานตรวจสอบ</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-bold text-slate-600">ตั้งแต่วันที่<DatePicker value={from} onChange={setFrom}/></label><label className="text-xs font-bold text-slate-600">ถึงวันที่<DatePicker value={to} onChange={setTo}/></label><label className="text-xs font-bold text-slate-600">ทรัพยากร<input value={resource} onChange={e=>setResource(e.target.value)} placeholder="เช่น VEHICLE_REQUEST" className={input}/></label><label className="text-xs font-bold text-slate-600">ผลการดำเนินการ<select value={result} onChange={e=>setResult(e.target.value)} className={input}><option value="">ทั้งหมด</option>{Object.entries(results).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><div className="mt-4 flex justify-end gap-2"><button onClick={reset} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 px-4 text-sm font-bold"><X size={16}/>ล้างตัวกรอง</button><button onClick={load} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-teal-600 px-5 text-sm font-bold text-white"><RefreshCw size={16}/>ค้นหา</button></div></section>
  {error?<div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>:null}<section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-black">รายการ Audit Log</h2><p className="mt-1 text-xs text-slate-500">พบ {rows.length.toLocaleString("th-TH")} รายการ{loading?" · กำลังโหลด…":""}</p></div><div className="overflow-x-auto"><table className="min-w-[950px] w-full text-sm"><thead className="bg-slate-50 text-xs font-bold text-slate-600"><tr><th className="px-4 py-3 text-left">วันเวลา</th><th className="px-4 py-3 text-left">ผู้ใช้งาน</th><th className="px-4 py-3 text-left">การดำเนินการ</th><th className="px-4 py-3 text-left">ทรัพยากร</th><th className="px-4 py-3 text-left">ผลลัพธ์</th><th className="px-4 py-3 text-left">รหัสอ้างอิง</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((r)=><tr key={r.publicId||r.id}><td className="px-4 py-3 whitespace-nowrap">{new Date(r.createdAt).toLocaleString("th-TH-u-ca-buddhist")}</td><td className="px-4 py-3">{r.user?.nameTh||[r.user?.firstnameTh,r.user?.lastnameTh].filter(Boolean).join(" ")||"ไม่ระบุ"}</td><td className="px-4 py-3 font-semibold">{r.action}</td><td className="px-4 py-3">{r.resource}</td><td className="px-4 py-3">{results[r.result]||r.result}</td><td className="px-4 py-3 text-xs text-slate-500">{r.resourceId||"-"}</td></tr>)}{!loading&&!rows.length?<tr><td colSpan={6} className="px-4 py-12 text-center text-slate-500">ไม่พบข้อมูลตามเงื่อนไข</td></tr>:null}</tbody></table></div></section></div>;
}
